= Hibernate Search documentation
:awestruct-layout: project-documentation
:awestruct-project: search

== Guides

link:/search/documentation/getting-started[Getting started guide]::
For a gentle introduction to the concepts of Hibernate Search without being sidetracked by other technologies.
link:/search/documentation/migrate/5.0[Migration guide]::
Helping you to upgrade your existing Search application to the latest and greatest.
link:http://example.com/ticket-monster[TicketMonster tutorial]::
Describes how to add a full-text search engine step by step from an existing Java EE application.

== Books and Articles

http://emmanuelbernard.com/books/hsia/[Hibernate Search in Action]::
A bit outdated book on Hibernate Search but a very good reference on the product and search engines in general.
It has been written by a member of the Hibernate Search team.

== Other documentation

Make sure to check the link:/search/faq/[FAQ].
Last but not least, you can find some additional documentation in our https://community.jboss.org/en/hibernate/search[wiki].
