= Documentation
:awestruct-layout: project-documentation
:awestruct-project: search
:page-interpolate: true
// TODO Remove the override when 6.0 is released as stable
//:guides_version_family: #{latest_stable_release(page).version_family}
:guides_version_family: 6.0

== Guides

link:https://docs.jboss.org/hibernate/search/{guides_version_family}/reference/en-US/html_single/#getting-started[Getting started guide]::
For a gentle introduction to the concepts of Hibernate Search without being sidetracked by other technologies.
link:/search/documentation/migrate/[Migration guides]::
Helping you to upgrade your existing Search application to the latest and greatest.

== Books and Articles

http://emmanuelbernard.com/books/hsia/[Hibernate Search in Action]::
A bit outdated book on Hibernate Search but a very good reference on the product and search engines in general.
It has been written by members of the Hibernate Search team.

== Maintainers

link:/search/documentation/maintain[This page] will only be of interest to maintainers of Hibernate Search.

== Other documentation

link:/search/faq/[FAQ]::
Frequently asked questions.
link:https://developer.jboss.org/en/hibernate/search[JBoss-Developer wiki]::
Old wiki hosted at JBoss.org. Mostly out-of-date content.
link:https://docs.jboss.org/hibernate/search/{guides_version_family}/internals/html_single/[Internals]::
An introduction to the internals of Hibernate Search for contributors.
