= Getting Help
:toc:
:awestruct-layout: support-standard

Using Hibernate in your application? Here are various options to get assistance.

== Community Support

Community support refers to assistance provided by users and developers of Hibernate projects,
be it for troubleshooting, fixing bugs, or developing new features.

[NOTE]
====
This is provided free-of-charge and thus without any guarantee.

In particular, the Hibernate team focuses its efforts on the latest stable versions.
====

See:

* The link:/community[community page] for more information on how to get assistance from the community.
* The link:/support/maintenance-policy[maintenance policy] to know how the Hibernate team decides which versions get maintained.
* The link:/support/compatibility-policy[compatibility policy] to know where breaking changes should be expected.

== Commercial, Long-Term Support

Application developers requiring longer support windows and/or contractually binding guarantees
should look for long-term support.

See link:/support/long-term[long-term support] for available commercial offerings.

== Commercial, End-of-Life Support

Application developers temporarily unable to upgrade from end-of-life versions of Hibernate projects
but still requiring fixes for security vulnerabilities
should look for end-of-life support.

See link:/support/end-of-life[end-of-life support] for available commercial offerings.
