:awestruct-layout: project-releases-series
:awestruct-project: search
:awestruct-series_version: "7.1"
:page-interpolate: true
:latest-release-version: #{series(page, page.series_version).releases.first.version}
:hsearch-doc-url-prefix: #{reference_doc(site.projects[page.project], series(page, page.series_version)).html_url}

=== Dependency upgrades

[[lucene-version]]
Lucene::
The Lucene backend now uses Lucene 9.9.
Besides other improvements it brings better vector search performance.
[[elasticsearch-version]]
Elasticsearch::
The Elasticsearch backend works with Elasticsearch 8.12 as well as other versions that were already compatible.

[[vector-search]]
=== Vector search for Lucene and Elasticsearch Backends

Hibernate Search now allows vector search in Lucene and Elasticsearch backends as an incubating feature.
Vector search provides the tools to search over binary (images, audio or video) or text data:
external tools convert that data to vectors (arrays of bytes or floats, also called "embeddings"),
which are then used for indexing and queries in Hibernate Search.
Hibernate Search introduces a new field type -- `@VectorField` and a new predicate `knn`, so that the vectors can be indexed
and then searched upon.

Vector fields can work with vector data represented as `byte` or `float` arrays in the documents.
Out of the box `byte[]` and `float[]` property types will work with the new field type. For any other entity property types,
a custom link:{hsearch-doc-url-prefix}#binding-valuebridge[value bridge]
or link:{hsearch-doc-url-prefix}#binding-valuebridge-valuebinder[value binder] should be implemented.
Keep in mind that indexed vectors *must* be of the same length
and that this length should be specified upfront for the schema to be created:

[source, Java, indent=0, subs="+attributes"]
----
@Entity
@Indexed
public class Book {

	@Id
	private Integer id;

	@VectorField(dimension = 512)
	private float[] coverImageEmbeddings;

	// Other properties ...
}
----

Searching for vector similarities is performed via a `knn` predicate:

[source, Java, indent=0, subs="+attributes"]
----
float[] coverImageEmbeddingsVector = /*...*/

List<Book> hits = searchSession.search( Book.class )
.where( f ->
    // provide the number of similar documents to look for:
    f.knn( 5 )
        // the name of the vector field:
        .field( "coverImageEmbeddings" )
         // matched documents will be the ones whose indexed vector
         // is "most similar" to this vector
        .matching( coverImageEmbeddingsVector )
    // additionally an optional filter can be supplied
    // to provide a regular fulltext search predicate
    .filter( f.match().field( "authors.firstName" ).matching( "arthur" ) )
).fetchHits( 20 );
----

Note that each backend may have its own specifics and limitations with regard to the vector search.
For more details look at the related link:{hsearch-doc-url-prefix}#search-dsl-predicate-knn-limitations[documentation].

[[metamodel-field-capabilities]]
=== Looking up the capabilities of each field in the metamodel

It is now possible to see which capabilities (predicates/sorts/projections/etc.)
are available for a field when link:{hsearch-doc-url-prefix}#mapping-inspect[inspecting the metamodel]:

[source, Java, indent=0, subs="+attributes"]
----
SearchMapping mapping = /*...*/ ;
// Retrieve a SearchIndexedEntity:
SearchIndexedEntity<Book> bookEntity = mapping.indexedEntity( Book.class );
// Get the descriptor for that index.
// The descriptor exposes the index metamodel:
IndexDescriptor indexDescriptor = bookEntity.indexManager().descriptor();

// Retrieve a field by name
// and inspect its capabilities if such field is present:
indexDescriptor.field( "releaseDate" ).ifPresent( field -> {
	if ( field.isValueField() ) {
		// Get the descriptor for the field type:
		IndexValueFieldTypeDescriptor type = field.toValueField().type();
		// Inspect the "traits" of a field type:
		// each trait represents a predicate/sort/projection/aggregation
		// that can be used on fields of that type.
		Set<String> traits = type.traits();
		if ( traits.contains( IndexFieldTraits.Aggregations.RANGE ) ) {
			// ...
		}
		if ( traits.contains( IndexFieldTraits.Predicates.EXISTS ) ) {
			// ...
		}
		// ...
	}
} );
----