= How to build hibernate.org
ifdef::env-github[:outfilesuffix: .adoc]
ifndef::env-github[:outfilesuffix: /]
:awestruct-layout: title-nocol
:toc:
:toc-placement: preamble

A bit of Git, a bit of Ruby and you will get your local hibernate.org served.

[[get-the-source]]
== Get the source

[source]
----
> git clone git@github.com:hibernate/hibernate.org.git
> cd hibernate.org
----

== Set up the build environment -- the easy way

The easiest way to set up a build environment is to use docker.

See https://github.com/hibernate/awestruct-build-env.

== Set up the build environment -- the hard way

If you want to run everything directly on your machine without using Docker, first good luck,
and then you'll need to reproduce the environment detailed in 
https://github.com/hibernate/awestruct-build-env/blob/main/Dockerfile.

[[awestruct-setup]]
=== Setup awestruct

[source]
----
> rake setup
----

== Serve the site locally

[source]
----
rake preview
----

Point your browser to http://localhost:4242

== Tips & Tricks

=== How to edit/publish content

Refer to this link:/survival-guide{outfilesuffix}[guide]

=== Which other tasks exist in the Rake build file?

[source]
----
> rake --tasks
----

This will list the available tasks with a short description

=== I am getting errors when trying to execute *awestruct* directly

You need to use `bundle exec <command>` to make sure you get all required Gems. Check the *Rakefile*
to see how the different awestruct calls are wrapped.

=== If you are getting error after an update

----
> rake clean[all]
> rake setup
> rake preview
----

=== If your changes are not visible...

Panic! Then completely regenerate the site via:

[source]
----
> rake clean preview
----

== License

The content of this repository is released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[ASL 2.0].

By submitting a "pull request" or otherwise contributing to this repository, you
agree to license your contribution under the respective licenses mentioned above.

== Acknowledgements

This website uses https://github.com/jbossorg/bootstrap-community[JBoss Community Bootstrap].

