= Articles and more
:awestruct-layout: project-standard
:awestruct-project: search

Articles, talks and books about Hibernate Search, the most recent ones first.

If you want to add something to the list, link:/community/[contact us]!

If you're looking for the official getting started guide or reference documentation,
see link:/search/documentation[here] instead.

== Current version

https://community.elastic.co/events/details/elastic-france-presents-elastic-paris-meetup-70-elasticsearch-et-hibernate-search-6/[[French\] Retour d'expérience : Elasticsearch x Hibernate Search 6]::
A presentation of Hibernate Search 6 and its use in a https://quarkus.io/[Quarkus] application,
focusing on Elasticsearch and https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#search-mapping-bridge[custom bridges].
+
Demo code: https://github.com/Sedona-Solutions/beer-manager-hibernate-search

https://www.heise.de/hintergrund/Hibernate-Search-Volltextsuche-in-Spring-Boot-Projekten-6028830.html[[German\] Hibernate Search: Volltextsuche in Spring-Boot-Projekten]::
A presentation of Hibernate Search 6 and its use in a https://spring.io/projects/spring-boot[Spring Boot] application.

https://www.youtube.com/watch?v=hwxWx-ORVwM[Quarkus Insights #32: Hibernate Search]::
A discussion of Hibernate Search 6 in https://quarkus.io/[Quarkus], how to use it and how it helps.
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-feature-examples[here].

https://peter-mueller.gitlab.io/blog/post/2020/11/18/restful-search-with-spring-and-hibernate-search-6/[RESTful Search with Spring and Hibernate Search 6]::
A tutorial on how to quickly create a REST API based on https://spring.io/[Spring] and Hibernate Search 6,
using either the Apache Lucene backend or the Elasticsearch backend.

https://quarkus.io/guides/hibernate-search-orm-elasticsearch[Quarkus - Hibernate Search guide]::
The official guide for the Hibernate Search extension in https://quarkus.io/[Quarkus].

https://in.relation.to/2019/11/12/hibernate-search-quarkus/[Hibernate Search in Quarkus]::
A tutorial using Hibernate Search 6 and https://quarkus.io/[Quarkus].
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-quarkus[here].

== 6.0 Alphas/Betas (slightly different API, but still relevant)

https://www.javaadvent.com/2020/12/how-to-keep-elasticsearch-in-sync-with-relational-databases.html[How to Keep Elasticsearch in Sync with Relational Databases?]::
A tutorial using Hibernate Search 6 and https://quarkus.io/[Quarkus].
+
Demo code: https://github.com/hakdogan/hibernate-search[here].

https://archive.fosdem.org/2019/schedule/event/hibernate_search_6/[From table to index (and back) with Hibernate Search 6]::
A presentation of Hibernate Search 6 and how it provides integration of Elasticsearch with a relational database.
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-elasticsearch-wikipedia[here].

== 5.x and below (completely different API)

https://reflectoring.io/hibernate-search/[Full-Text Search with Hibernate Search and Spring Boot]::
A tutorial using Hibernate Search 5 and https://spring.io/projects/spring-boot[Spring Boot].

Add full-text search to your application with Hibernate Search::
A tutorial using Hibernate Search 5.
+
https://thorben-janssen.com/add-full-text-search-application-hibernate-search/[Part 1] explains the basics.
+
https://thorben-janssen.com/implement-complex-full-text-search-hibernate-search/[Part 2] deals with more complex analysis.
+
https://thorben-janssen.com/use-facets-categorize-fulltextquery-results/[Part 3] deals with faceted search.

https://vimeo.com/181788146[From Hibernate to Elasticsearch in no time]::
A presentation of the integration of Hibernate Search 5 with Elasticsearch.
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-with-elasticsearch[here].

http://emmanuelbernard.com/books/hsia/[Hibernate Search in Action]::
A slightly outdated book on Hibernate Search but a very good reference on the product and search engines in general.
It was written by members of the Hibernate Search team at the time.
