= Contribute
Emmanuel Bernard
:awestruct-layout: project-contribute
:awestruct-project: search

Thanks for your interest! Hibernate Search is an open source project and community.
We love contributions that scratch somebody's own itch: they bring the project forward.

== What to contribute

You can contribute anything from code to test to documentation.
If you do not have a specific itch to scratch, you can find the https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20status%20in%20(Open%2C%20Reopened%2C%20%22Awaiting%20Test%20Case%22)%20AND%20%22Suitable%20for%20new%20contributors%22%20%3D%20%22Yes%2C%20likely%22%20ORDER%20BY%20updated%20DESC[list of tasks] suitable for new contributors.

== How to contribute

*Do share early and often. Don't be afraid, make the jump.*

In good open source way, it is better to share a prototype and get input from everyone.
We love GitHub pull requests. This is our way to discuss features, review and share code.
So fork our repository and send a pull request. We are waiting.

You can find more information on how to start contributing
on the https://github.com/hibernate/hibernate-search/blob/main/CONTRIBUTING.md[CONTRIBUTING file]
at the root of the git repository.

== Maintainers

If you've recently joined the team and need to know more about CI or releases,
you can find a maintainer guide
in the https://github.com/hibernate/hibernate-search/blob/main/MAINTAINERS.md[MAINTAINERS file]
at the root of the git repository.
