= Hibernate Search Downloads
:awestruct-layout: project-downloads
:awestruct-project: search
:page-interpolate: true
:nexus: https://repository.jboss.org/nexus/
:nexus-search: https://repository.jboss.org/nexus/index.html#nexus-search;gav~#{site.projects.search.group_id}~#{site.projects.search.artifact_id}~~~
:groupId: #{site.projects.search.group_id}
:artifactId: #{site.projects.search.artifact_id}
:version: #{site.projects.search.sorted_releases.first.version}

== Maven repository

Hibernate Search is built using Maven and publishes as part of the release process the project artifacts to the
{nexus}[JBoss Maven Repository] under {nexus-search}[{groupId}:{artifactId}]. 
For more information on how to configure Maven to use JBoss's repository,
http://community.jboss.org/wiki/MavenGettingStarted-Users[look here] or use `mvn install -s setting-example.xml`.

Here is how to declare the dependency in your Maven POM file

[source,xml]
[subs="verbatim,attributes"]
.Maven dependency
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>{artifactId}</artifactId>
    <version>{version}</version>
</dependency>
----

[[supported-versions]]
== Supported versions pass:[<i class="icon-user-md icon-fixed-width icon-2x"></i>]

Hibernate Search is a fully supported component of both the following products:

* http://www.redhat.com/en/technologies/jboss-middleware/application-platform[Red Hat JBoss Enterprise Application Platform]
* https://www.redhat.com/products/jbossenterprisemiddleware/web-framework-kit/[Red Hat JBoss Web Framework Kit]

In addition the following product provides optional extensions such as high performance real time replication:

* http://www.redhat.com/en/technologies/jboss-middleware/data-grid[Red Hat JBoss Data Grid]

If you are looking for Hibernate Search support, contact Red Hat.
