= More resources
:awestruct-layout: project-standard
:awestruct-project: search

Third-party documentation, blog posts, talks and books about Hibernate Search, the most recent ones first.

If you want to add something to the list, link:/community/[contact us]!

== Official documentation

If you're looking for the official getting started guide or reference documentation,
see link:/search/documentation[here] instead.

== Third-party documentation

https://quarkus.io/guides/hibernate-search-orm-elasticsearch[Quarkus - Hibernate Search - ORM + Elasticsearch]::
The https://quarkus.io/[Quarkus] guide to use Hibernate Search with Hibernate ORM and Elasticsearch/OpenSearch.

https://quarkus.io/guides/hibernate-search-standalone-elasticsearch[Quarkus - Hibernate Search - Standalone + Elasticsearch]::
The https://quarkus.io/[Quarkus] guide to use Hibernate Search in Standalone mode with Elasticsearch/OpenSearch.

== Blog posts

https://quarkus.io/blog/search-indexing-rollover/[Leveraging Hibernate Search capabilities in a Quarkus application without a database]::
This is the second post in the quarkus.search.io series on using the Hibernate Search Standalone mapper
to mass index data from a set of flat files without initially knowing the total number of entities and reading the files just once.
+
The quarkus.search.io application code: https://github.com/quarkusio/search.quarkus.io

https://quarkus.io/blog/search-indexing-rollover/[Indexing rollover with Quarkus and Hibernate Search]::
This is the first post in the quarkus.search.io series on reindexing all search data
without downtime when using Hibernate Search and an Elasticsearch backend.
+
The quarkus.search.io application code: https://github.com/quarkusio/search.quarkus.io

Build a Spring Boot REST API with Full-Text Search using Hibernate Search::
A tutorial on how to quickly create a REST API based on https://spring.io/projects/spring-boot/[Spring Boot] and Hibernate Search 6,
using the Apache Lucene backend.
+
https://gauthier-cassany.com/posts/spring-boot-hibernate-search[Part 1] explains the basics.
Demo code: https://github.com/Mozenn/spring-boot-hibernate-search
+
https://gauthier-cassany.com/posts/spring-boot-paginated-search[Part 2] adds pagination.
Demo code: https://github.com/Mozenn/spring-boot-paginated-search
+
Alternate links:
https://dev.to/mozenn/build-a-spring-boot-rest-api-with-full-text-search-using-hibernate-search-4a67[dev.to],
https://medium.com/javarevisited/build-a-spring-boot-rest-api-with-full-text-search-using-hibernate-search-88d83bfae5bb[medium.com].

https://www.heise.de/hintergrund/Hibernate-Search-Volltextsuche-in-Spring-Boot-Projekten-6028830.html[[German\] Hibernate Search: Volltextsuche in Spring-Boot-Projekten]::
A presentation of Hibernate Search 6 and its use in a https://spring.io/projects/spring-boot[Spring Boot] application.

https://peter-mueller.gitlab.io/blog/post/2020/11/18/restful-search-with-spring-and-hibernate-search-6/[RESTful Search with Spring and Hibernate Search 6]::
A tutorial on how to quickly create a REST API based on https://spring.io/[Spring] and Hibernate Search 6,
using either the Apache Lucene backend or the Elasticsearch backend.
+
Demo code: https://gitlab.com/peter-mueller/spring-hibernate-search-6-demo

https://in.relation.to/2019/11/12/hibernate-search-quarkus/[Hibernate Search in Quarkus]::
A tutorial using Hibernate Search 6 and https://quarkus.io/[Quarkus].
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-quarkus

== Talks and videos

https://www.youtube.com/live/ThH8sJC69zU[Quarkus Insights #171: Hibernate Search 7.1 & Vector Search]::
A discussion and demonstration of vector search features in Hibernate Search 7.1 in the context of https://quarkus.io/[Quarkus].
+
Links to illustrations/slides: https://github.com/marko-bekhta/quarkus-insights-demo-hibernate-search-vectors#links
+
Demo code: https://github.com/marko-bekhta/quarkus-insights-demo-hibernate-search-vectors

https://www.youtube.com/watch?v=CpfnoMRhHew[[French\] Hibernate Search 7: Nouveautés et cas pratiques de la recherche full-text et vectorielle Java]::
A presentation of new features in Hibernate Search 6/7, including vector search.
+
Slides: https://yrodiere.github.io/talks/2024-04-devoxx-france-hsearch-7/
+
Demo code: https://github.com/yrodiere/devoxx-france-2024-hibernate-search-demo

https://www.youtube.com/watch?v=cZCIQFJVv_Q[Quarkus Insights #154: Using Hibernate to improve search on Quarkus.io]::
A real-world example of using Hibernate Search to index the https://quarkus.io/guides[Quarkus documentation].
+
Application code: https://github.com/quarkusio/search.quarkus.io

https://www.youtube.com/watch?v=0-e4wkRwTIo[Quarkus Insights #145: What’s new in Hibernate Search]::
A discussion of new features in Hibernate Search 6.1/6.2 in the context of https://quarkus.io/[Quarkus].
+
Slides: https://yrodiere.github.io/presentation/2023-11-quarkus-insights-whats-new-hibernate-search/
+
Demo code:
+
* Demo 1 (search): https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-feature-examples/search-advanced
* Demo 2 (outbox polling): https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-outbox-polling

https://2023.rivieradev.fr/session/1140[[French\] Recherche plein-texte distribuée avec Quarkus, Hibernate ORM, Hibernate Search et Elasticsearch]::
A presentation of outbox-polling coordination in Hibernate Search 6.1+, with a demo using https://quarkus.io/[Quarkus].
+
Slides: https://yrodiere.github.io/presentation/2023-07-rivieradev-quarkus-hsearch/
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-outbox-polling

https://community-conference.elastic.co/session/305406[[French\] ElasticCC: Indexation au fil de l'eau de données relationnelles via Hibernate Search]::
A presentation of Hibernate Search 6 to Elasticsearch users.
+
Slides: https://yrodiere.github.io/presentation/2022-02-elasticCC-hsearch-6-es/
+
Alternate link (YouTube): https://www.youtube.com/watch?v=Lgi9DmgYkuQ.

https://community.elastic.co/events/details/elastic-france-presents-elastic-paris-meetup-70-elasticsearch-et-hibernate-search-6/[[French\] Retour d'expérience : Elasticsearch x Hibernate Search 6]::
A presentation of Hibernate Search 6 and its use in a https://quarkus.io/[Quarkus] application,
focusing on Elasticsearch and https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#search-mapping-bridge[custom bridges].
+
Demo code: https://github.com/Sedona-Solutions/beer-manager-hibernate-search

https://www.youtube.com/watch?v=Nnh_DuzA3BM[Hibernate Search with Quarkus]::
A demonstration of how to use Hibernate Search in a Vue.js webapp with a REST backend using Quarkus 2.7.
+
Demo code: https://github.com/redhat-mw-demos/quarkus-hibernate-search-starter-demo

https://www.youtube.com/watch?v=hwxWx-ORVwM[Quarkus Insights #32: Hibernate Search]::
A discussion of Hibernate Search 6 in https://quarkus.io/[Quarkus], how to use it and how it helps.
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-feature-examples

== Resources for older versions

=== Hibernate Search 6.0 Alphas/Betas (slightly different API, but still relevant in 6.0+)

https://www.javaadvent.com/2020/12/how-to-keep-elasticsearch-in-sync-with-relational-databases.html[How to Keep Elasticsearch in Sync with Relational Databases?]::
A tutorial using Hibernate Search 6 and https://quarkus.io/[Quarkus].
+
Demo code: https://github.com/hakdogan/hibernate-search

https://archive.fosdem.org/2019/schedule/event/hibernate_search_6/[From table to index (and back) with Hibernate Search 6]::
A presentation of Hibernate Search 6 and how it provides integration of Elasticsearch with a relational database.
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-elasticsearch-wikipedia

=== Hibernate Search 5.x and below (completely different API)

https://reflectoring.io/hibernate-search/[Full-Text Search with Hibernate Search and Spring Boot]::
A tutorial using Hibernate Search 5 and https://spring.io/projects/spring-boot[Spring Boot].

Add full-text search to your application with Hibernate Search::
A tutorial using Hibernate Search 5.
+
https://thorben-janssen.com/add-full-text-search-application-hibernate-search/[Part 1] explains the basics.
+
https://thorben-janssen.com/implement-complex-full-text-search-hibernate-search/[Part 2] deals with more complex analysis.
+
https://thorben-janssen.com/use-facets-categorize-fulltextquery-results/[Part 3] deals with faceted search.

https://vimeo.com/181788146[From Hibernate to Elasticsearch in no time]::
A presentation of the integration of Hibernate Search 5 with Elasticsearch.
+
Demo code: https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-with-elasticsearch

http://emmanuelbernard.com/books/hsia/[Hibernate Search in Action]::
A slightly outdated book on Hibernate Search but a very good reference on the product and search engines in general.
It was written by members of the Hibernate Search team at the time.

link:https://developer.jboss.org/en/hibernate/search[JBoss-Developer wiki]::
Old wiki hosted at JBoss.org. Mostly out-of-date content.
