= Roadmap
:awestruct-layout: project-roadmap
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/5.11/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: milestones are released regularly, the Final release is tagged when it's considered stable.

== Hibernate Search 7.0

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%207.0-backlog%20ORDER%20BY%20created%20DESC[here].

Upgrade baseline requirements::
Upgrade to newer versions of dependencies and drop compatibility with older technologies.
In particular:

* link:{hsearch-jira-url-prefix}/HSEARCH-4556[HSEARCH-4556] Require JDK 11 (at least)
* link:{hsearch-jira-url-prefix}/HSEARCH-4393[HSEARCH-4393] Upgrade to Lucene 9.x (which requires JDK 11)
* link:{hsearch-jira-url-prefix}/HSEARCH-4394[HSEARCH-4394] Switch from Java EE to Jakarta EE
* link:{hsearch-jira-url-prefix}/HSEARCH-4395[HSEARCH-4395] Upgrade to Hibernate ORM 6 (with requires Jakarta EE instead of Java EE) and drop compatibility with Hibernate ORM 5

== Hibernate Search 7.1

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%207.1-backlog%20ORDER%20BY%20created%20DESC[here].

Mass indexing improvements::
In particular:

* link:{hsearch-jira-url-prefix}/HSEARCH-3499[HSEARCH-3499] Near-zero-downtime mass indexing when the schema did not change
* link:{hsearch-jira-url-prefix}/HSEARCH-1032[HSEARCH-1032] MassIndexer with an update mechanism
* link:{hsearch-jira-url-prefix}/HSEARCH-521[HSEARCH-521] Improve performance of MassIndexer through Eager fetching

Search query features::
Add more features to the Hibernate Search DSL.
In particular:

* link:{hsearch-jira-url-prefix}/HSEARCH-917[HSEARCH-917] Add match all terms option when matching in the DSL API
* link:{hsearch-jira-url-prefix}/HSEARCH-3327[HSEARCH-3327] Add options for match predicates targeting multiple fields
* link:{hsearch-jira-url-prefix}/HSEARCH-3926[HSEARCH-3926] Predicate on multiple fields designated by a single label/group name/etc. ("_all", copy_to, ...)

== Hibernate Search 7.2

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%207.2-backlog%20ORDER%20BY%20created%20DESC[here].

More advanced mapping::
Allow more complex setups when it comes to mapping entities to indexes. In particular:

* link:{hsearch-jira-url-prefix}/HSEARCH-3971[HSEARCH-3971] Mapping an entity differently based on a discriminator
* link:{hsearch-jira-url-prefix}/HSEARCH-3683[HSEARCH-3683] Mapping a single entity type to multiple indexes
* link:{hsearch-jira-url-prefix}/HSEARCH-3903[HSEARCH-3903] Filters based exclusively on mapper metadata for @IndexedEmbedded
Some specialized field types::
Add commonly used field types. In particular:

* Fields derived from large blobs, useful when
  link:{hsearch-jira-url-prefix}/HSEARCH-3350[indexing PDFs with Apache Tika] for example.
* Maybe more, depending on demand, e.g.
  link:{hsearch-jira-url-prefix}/HSEARCH-3488[HSEARCH-3488] Add support for nanosecond precision for temporal fields.
Tracing::
Tracing of search queries and indexing requests to enable easier debugging and performance investigation.
+
See link:{hsearch-jira-url-prefix}/HSEARCH-4057[HSEARCH-4057].

== Hibernate Search 7.x or later

Free-form indexing::
We're planning to decouple the metadata definition from annotated java classes, to allow better indexing of other more flexible sources;
for example to make it easier to index data structured in the JSON format, or other formats whose schema is not known at compile time.
Debezium integration::
Asynchronous indexing driven by Change Data Capture in the database instead of Hibernate ORM events.
+
This would allow capturing changes caused by any SQL command, not just those issued by Hibernate ORM.
+
See link:{hsearch-jira-url-prefix}/HSEARCH-3513[HSEARCH-3513].
Reactive Search::
Experiment with integrating Hibernate Search with Hibernate Reactive.
+
See also link:{hsearch-jira-url-prefix}/HSEARCH-3322[HSEARCH-3322],
link:{hsearch-jira-url-prefix}/HSEARCH-3471[HSEARCH-3471].