= Roadmap
:awestruct-layout: project-roadmap
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: milestones are released regularly, the Final release is tagged when it's considered stable.

== Hibernate Search 8.0

The main goals for the 8.0 series are:

* introduce the static metamodel as an incubating feature (link:{hsearch-jira-url-prefix}/HSEARCH-4951[HSEARCH-4951])
* provide integration with Hibernate ORM 7.0 (link:{hsearch-jira-url-prefix}/HSEARCH-5082[HSEARCH-5082])

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%208.0-backlog%20ORDER%20BY%20created%20DESC[here].

== Hibernate Search 8.1

The main goals for the 8.1 series are:

* introduce the bucket aggregations (link:{hsearch-jira-url-prefix}/HSEARCH-3661[HSEARCH-3661])
* continue improving the static metamodel, in particular look into generating finder methods (link:{hsearch-jira-url-prefix}/HSEARCH-4953[HSEARCH-4953])
* experiment with Maven 4 (link:{hsearch-jira-url-prefix}/HSEARCH-5304[HSEARCH-5304])
* introduce the extended (platform) BOM (link:{hsearch-jira-url-prefix}/HSEARCH-5356[HSEARCH-5356])

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%208.1-backlog%20ORDER%20BY%20created%20DESC[here].

== Hibernate Search 8.2

The main goals for the 8.2 series are:

* Near-zero-downtime reindexing (link:{hsearch-jira-url-prefix}/HSEARCH-4954[HSEARCH-4954])
* Readonly indexes (link:{hsearch-jira-url-prefix}/HSEARCH-5261[HSEARCH-5261])
* Suggesters (link:{hsearch-jira-url-prefix}/HSEARCH-5357[HSEARCH-5357])
* Integration with the stateless Hibernate ORM session (link:{hsearch-jira-url-prefix}/HSEARCH-5339[HSEARCH-5339])

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%208.2-backlog%20ORDER%20BY%20created%20DESC[here].

== Hibernate Search 9.0

The main goal for the 9.0 series would be to explore an alternative approach to index mapping,
where the index structure is described as a set of annotated records.

== Later

If the feature you are looking for is not on the roadmap,
look for it https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20resolution%20not%20in%20(%22Fixed%22)%20AND%20fixVersion%20%3D%20EMPTY%20ORDER%20BY%20created%20DESC[here]
or link:{hsearch-jira-url-prefix}/HSEARCH[submit a Jira issue],
and consider link:/search/contribute/[contributing].
