= Hibernate Search roadmap
Emmanuel Bernard, Sanne Grinovero
:awestruct-layout: project-frame
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: while milestones are released regularly, the Final release is tagged when it's considered stable.

== Hibernate Search 5.4

First version to targer Hibernate ORM 5 compatibility.

Hibernate ORM 5::
This version will be compatible with Hibernate ORM version `5`, but will also *require* it.
To allow you to focus on upgrading the Hibernate ORM related components in your applications, we're keeping changes in Hibernate Search extremely limited.
Transactional JMS backend::
Since the JMS queue could optionally be transactional, we're working on adding an option to submit indexing changes to the backend within
the database transaction rather than after it. See also link:$$http://in.relation.to/2015/07/09/hibernate-search-jms-transaction/$$[related in.relation.to post].
WildFly 10::
WildFly 10 is going to include Hibernate ORM 5, so the JBoss Modules we produce will be meant for WildFly 10 primarily.
Other dependency upgrades::
To align with Hibernate ORM 5 and WildFly 10, we'll upgrade relevant dependencies such as JBoss Logging and Hibernate Commons Annotations.
Java 9 compatibibility::
We're aiming at regularly testing compatibility with Java 7, 8 and now 9 too. Java 7 will still be the minimum requirement.

== Hibernate Search  5.5

Moving from Apache Lucene 4 to Apache Lucene 5.

Apache Lucene 5::
This version is expected to be compatible (and require) the latest Apache Lucene in the version 5.x series.
As for any minor version, we aim at not breacking backwards compatibility but it's very likely that some features will have to be deprecated
as this upgrade introduces some significant changes.
Infinispan Directory::
This component has been moved into the Infinispan project, and will be removed from Hibernate Search.


== Hibernate Search 5.6

Experimental new backends.

Pre-analysis of text in the transaction context::
We will explore the option to compute the text analysis on the slave nodes, to improve remoting/clustering & scalability.
Removing this step from the master nodes will eventually allow to have "indexing only" nodes which don't need to have entities deployed.
Experimental additional backends::
Some additional backends are being explored, such as storing changes in a relational database rather than in a queue, or delegate
to Lucene servers such as ElasticSearch or Apache Solr. These might need to be pushed to 6.0 if they require public API changes.
Community help would be very welcome, as we have good experience with Lucene but not with the REST based products.
Out of the box FieldBridge for more types::
To provide out of the box indexing support for new common types, such as the Java8 date/time value types and
the new Spatial types included in Hibernate ORM 5. Maybe also Joda Time if there is enough interest.
Improved reliability in clusters::
We expect to provide some documentation and examples on how to achieve highly reliable failover configurations of the
master/slave architecture used by Hibernate Search.

== Hibernate Search 6.0

API refresh to better match all new features from Lucene 5, free-form indexing and the new backends.

Apache Lucene 5 related improvements::
To provide the full power of some of the new features in Apache Lucene 5, some API changes are needed.
These API changes - when disruptive - will have to wait a major version such as 6.0.
Better integration for new backends::
The new integrations and backends will likely need significant API changes.
Free-form indexing::
We're planning to decouple the metadata definition from annotated java classes, to allow better
indexing of other more flexible sources.


