= Roadmap
Emmanuel Bernard, Sanne Grinovero, Yoann Rodière
:awestruct-layout: project-roadmap
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: milestones are released regularly, the Final release is tagged when it's considered stable.

== Hibernate Search 6.1

Restore the WildFly integration::
The WildFly integration was removed in 6.0 to reduce the work load.
We will restore it in 6.1.

First-class support for clustered applications::
Hibernate Search 6.0 only allows single-node applications,
or multi-node applications where each node works independently, simply sending events to an Elasticsearch cluster.
+
This does not account for several challenges that we will address in 6.1:

* When each node sends updates to Elasticsearch independently,
conflicts may arise when entities are updated simultaneously on different nodes.
There is a need to prevent, or at least resolve, these conflicts.
* For some use cases where maintenance downtime is not acceptable,
Hibernate Search needs to provide hot updates at the cluster level:
allow to boot application nodes with the new mapping,
while some application nodes with the old mapping are still running.

== Hibernate Search 6.x

Restore the OSGi integration::
The OSGi integration was removed in 6.0 to reduce the work load.
We will restore it in 6.1 if there is demand for it.
https://hibernate.atlassian.net/browse/HSEARCH-3279[Vote here].

Free-form indexing::
We're planning to decouple the metadata definition from annotated java classes, to allow better indexing of other more flexible sources;
for example to make it easier to index data structured in the JSON format, or other formats whose schema is not known at compile time.

