= Hibernate Search roadmap
Emmanuel Bernard, Sanne Grinovero
:awestruct-layout: project-frame
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: while milestones are released regularly, the Final release is tagged when it's considered stable.


== Hibernate Search 5.6

Experimental integration with Elasticsearch

Elasticsearch::
This version will sport an experimental integration with Elasticsearch, and aim at providing a reasonably useful
integration without breaking public APIs.
Performance::
Having now a robust integration with Apache Lucene 5.x, even though current performance is good we want
to make sure we're making the most of it.


== Hibernate Search 5.7

Improved modularity

WildFly Swarm::
WildFly Swarm is the new fine-grained modular version of WildFly aiming at microservices.
We should make sure Hibernate Search is integrated properly and the usage is documented.
Java 9 compatibibility::
We're aiming at regularly testing compatibility with Java 7, 8 and now 9 too.
Hibernate Search should test its modularity within project Jigsaw, within reason as we can't depent on Java9 release schedules.
Pre-analysis of text in the transaction context::
We will explore the option to compute the text analysis on the slave nodes, to improve remoting/clustering & scalability.
Removing this step from the master nodes will eventually allow to have "indexing only" nodes which don't need to have entities deployed.
Clustering::
The integration of a "master node" needs to be simplified, both in terms of user configuration and implementation.
We plan to not need user classes (entities) on such a node, so that in future it could be a separate download
which works out of the box with minimal configuration.


== Hibernate Search 6.x

API refresh to better match all new features from Lucene 5, free-form indexing and the new backends
such as Elasticsearch and standalone cluster nodes.

Apache Lucene 5 related improvements::
To provide the full power of some of the new features in Apache Lucene 5, some API changes are needed.
These API changes - when disruptive - will have to wait a major version such as 6.0.
Better integration for new backends::
The new integrations and backends will likely need significant API changes.
Free-form indexing::
We're planning to decouple the metadata definition from annotated java classes, to allow better
indexing of other more flexible sources.
Join operations:
Expose Lucene's index-time and query-time join capabilities.



