= Roadmap
:awestruct-layout: project-roadmap
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/5.11/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: milestones are released regularly, the Final release is tagged when it's considered stable.

== Hibernate Search 7.2

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%207.2-backlog%20ORDER%20BY%20created%20DESC[here].

* link:{hsearch-jira-url-prefix}/HSEARCH-4962[HSEARCH-4962] APIs to support Hibernate Search Tools
* link:{hsearch-jira-url-prefix}/HSEARCH-5133[HSEARCH-5133] Add metrics aggregations

== Hibernate Search 8.0

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%208.0-backlog%20ORDER%20BY%20created%20DESC[here].

* link:{hsearch-jira-url-prefix}/HSEARCH-4951[HSEARCH-4951] Static metamodel for Hibernate Search
* link:{hsearch-jira-url-prefix}/HSEARCH-5082[HSEARCH-5082] Upgrade to Hibernate ORM 7.0


== Hibernate Search 8.1

For a full list of issues currently planned for this series,
see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%208.1-backlog%20ORDER%20BY%20created%20DESC[here].

* link:{hsearch-jira-url-prefix}/HSEARCH-4974[HSEARCH-4970] Better observability in Hibernate Search
* link:{hsearch-jira-url-prefix}/HSEARCH-4977[HSEARCH-4977] Better highlighting/projections in nested fields
* link:{hsearch-jira-url-prefix}/HSEARCH-4954[HSEARCH-4954] Near-zero-downtime reindexing
* link:{hsearch-jira-url-prefix}/HSEARCH-4956[HSEARCH-4956] Reindexing for high-cardinality associations

== Later

If the feature you are looking for is not on the roadmap,
look for it https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20resolution%20not%20in%20(%22Fixed%22)%20AND%20fixVersion%20%3D%20EMPTY%20ORDER%20BY%20created%20DESC[here]
or link:{hsearch-jira-url-prefix}/HSEARCH[submit a Jira issue],
and consider link:/search/contribute/[contributing].
