= Hibernate Search roadmap
Emmanuel Bernard, Sanne Grinovero
:awestruct-layout: project-frame
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Search is a community driven project and as such the roadmap constantly evolves to reflect the users needs.

You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/HSEARCH[issue tracker] but this page is a good and concise view of where we are going.

Dates are generally omitted: while milestones are released regularly, the Final release is tagged when it's considered stable.


== Hibernate Search 5.8

Elasticsearch::
With support for Elasticsearch first introduced in version `5.6`, we aim to polish it further.
Plans are to make Elasticsearch versions `5+` compatible.

Performance::
Always learning new tricks! Especially the Elasticsearch integrations haven't been extensively tested in high scale scenarios.

Analyzers::
A new DSL will be introduced to allow people to define Analyzers programmatically at boostrap, as an alternative to the current `@Analyzer` and `@AnalyzerDef` annotations.
We might want to automatically register a set of commonly used Analyzers - let us know what you think of this as the choice is hard!

WildFly Swarm::
WildFly Swarm is the new fine-grained modular version of WildFly aiming at microservices.
We should make sure Hibernate Search is integrated properly and the usage is documented.

Java 9 compatibibility::
We're aiming at regularly testing compatibility with Java 7, 8 and now 9 too.
Hibernate Search should test its modularity within project Jigsaw, within reason as we can't depent on Java9 release schedules.

Removal of class definitions from master nodes::
The integration of a "master node" needs to be simplified, both in terms of user configuration and implementation.
We plan to not need user classes (entities) on such a node, so that in future it could be a separate download
which works out of the box with minimal configuration.


== Hibernate Search 6.x

Compatible with Hibernate ORM 6, Apache Lucene 6 (maybe 7).

API Refresh::
A significant API refresh is planned to better abstract from the Lucene API so that alternative backends such as Elasticsearch can be used without having Lucene on your classpath.
This will also benefit Lucene users, as the abstraction should allow us to automatically apply more optimisations without the user needing to be a Lucene expert.

Upgrade to Apache Lucene 6 (7)::
To provide the full power of some of the new features in Apache Lucene 6, some API changes are needed.
This includes some API improvements which could have been useful since the upgrade to Lucene 5, but we only apply breaking API changes in major releases.

Free-form indexing::
We're planning to decouple the metadata definition from annotated java classes, to allow better indexing of other more flexible sources.

Join operations::
Expose Lucene's index-time and query-time join capabilities.


