= Support
:awestruct-layout: project-standard
:awestruct-project: search

[[supported-versions]]
== Supported Products pass:[<i class="icon-user-md icon-fixed-width icon-2x"></i>]

Hibernate Search is available as an enterprise ready supported library as a component of the http://www.redhat.com/en/technologies/jboss-middleware/application-platform[Red Hat JBoss Enterprise Application Platform].

In addition the http://www.redhat.com/en/technologies/jboss-middleware/data-grid[Red Hat JBoss Data Grid] provides optional extensions such as high performance real time replication for Hibernate Search powered applications running on the Red Hat JBoss Enterprise Application Platform.

The Red Hat JBoss Data Grid also embeds a custom edition of Hibernate Search and allows using most of the same API to run high performance full-text queries and data mining on the data grid.

Several more products from Red Hat are powered by Hibernate Search.

If you are interested in Hibernate Search support/consulting within these platforms, please http://www.redhat.com/contact/sales.html[contact Red Hat]!
