:awestruct-layout: project-releases-series
:awestruct-project: search
:awestruct-series_version: "6.0"

[[preview-status]]
=== Preview status

Hibernate Search 6.0 is currently a *technology preview*.

While the core of Hibernate Search 6 is ready for use in a production environment,
there are still some limitations:

* APIs are expected to stay stable, but may still change if major implementation issues are detected.
* Some of the less frequently used features from Hibernate Search 5 are still missing.
* There may still be some performance bottlenecks.

If you encounter problems, be sure to https://hibernate.atlassian.net/browse/HSEARCH[report them]:
new preview versions are released regularly.

The exact features that are currently implemented and expected to work will be added to the reference documentation
as new Beta versions are released, but to sum up, here is what you can start to play with:

* ORM integration:
** Mapping of entities using either annotation mapping or programmatic mapping.
Most of the field types supported in Search 5 are supported in Search 6.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-mapping[mapping]
in the reference documentation.
** Custom, user-defined type bridges, property bridges or value bridges.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-bridge[bridges]
in the reference documentation.
** Automatic indexing of ORM entities on transaction commit or session flush (if outside of a transaction)
(enabled automatically if Hibernate Search is in your classpath and the entity is `@Indexed`).
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-indexing-automatic[automatic indexing]
in the reference documentation.
** Mass indexing of ORM entities that are already persisted in database.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-indexing-massindexer[mass indexing]
in the reference documentation.
** Searching for ORM entities using their Hibernate Search index,
and retrieving managed entities as results.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-query[query DSL]
in the reference documentation.
* Search DSL
** All the predicates available in Search 5, except `facet` and `moreLikeThis`.
Additionally, the new `id`, `nested` and `exists` predicates were added.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-predicate[predicate DSL]
in the reference documentation.
** All the sorts available in Search 5.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-sort[sort DSL]
in the reference documentation.
** All the projections available in Search 5.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-projection[projection DSL]
in the reference documentation.
** Aggregations, equivalent to the "faceting" feature of Search 5.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-aggregation[aggregation DSL]
in the reference documentation.


[[orm-version]]
=== ORM version

Hibernate Search 6 still relies on ORM 5.4 at the moment,
because it requires features that are not yet implemented in ORM 6 (still in development).

Note that only Hibernate ORM 5.4.4.Final or later will work correctly;
5.4.3.Final and earlier will not.

[[lucene-8]]
=== Lucene 8
// Old anchor, kept here to avoid dead links
[[lucene-7]]

The Lucene backend now uses Lucene 8.5.

[[elasticsearch-7]]
=== Elasticsearch 7
// Old anchor, kept here to avoid dead links
[[elasticsearch-6]]

The Elasticsearch backend now works with Elasticsearch 5.6, 6.8 or 7.6.
Support for older versions of Elasticsearch was dropped.

[[api-refresh]]
=== API refresh

A lot of APIs have been changed, for multiple reasons.

==== More consistent API types

The API types consistently use the `Search` prefix: no more mixing `FullText` with `Search` or simply no prefix.

Additionally, the `SearchQuery` type (previously `FullTextQuery`) now defines its own methods
instead of extending JPA's `TypeQuery`, allowing for an API that makes more sense considering that an index,
not a database, is being targeted.
It is still possible to create an adapter that implements JPA's `TypeQuery`.

==== No more Lucene in Hibernate Search APIs

Hibernate Search APIs now abstract from the Lucene APIs,
so that alternative backends such as Elasticsearch can be used without having Lucene on your classpath.

This should also allow us to upgrade the Lucene version more easily:
in Search 5, as Lucene was "part of" our APIs,
we were severely limited when we wanted to upgrade to a newer Lucene version,
because any breaking change in Lucene could mean a breaking change for our users, too.
Now that using Lucene APIs is no longer necessary to use Hibernate Search,
upgrades should be faster.

==== New Search DSL

The Search DSL is brand new, with several improvements:

* Ability to use lambdas for more concise query definition, even when queries are complex.
* Type-safe projections thanks to the brand new projection DSL.
* Various new features and improvements such as a new `exists` predicate,
the ability to override analyzers on a per-predicate basis, ...
* Injection of native predicates (`org.apache.lucene.search.Query` for Lucene, JSON for Elasticsearch)
within DSL-created predicates.
This is not new for the Lucene integration, but it is for the Elasticsearch integration.
See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-predicate-extensions[predicate extensions].
* Simpler syntax for predicates when targeting multiple types in a single query:
instantiating multiple `QueryBuilders` is no longer needed,
Hibernate Search takes into account that multiple types are targeted
and automatically checks that targeted fields are compatible across all targeted indexes.

[[bridge-2.0]]
==== Bridge 2.0

The bridge APIs had to change as part of the API refresh,
so we took this opportunity to overhaul bridge APIs to make bridges more powerful.

The new Bridge APIs are completely different, but with a lot of improvements:

* Custom (user-defined) bridge annotations, allowing to pass type-safe parameters, and not just strings.
* Better support for dirty checking optimization in bridges (in `TypeBridge` in particular),
by allowing bridges to declare what parts of the entity they use.
* Predicates on non-String fields will work without having to bypass bridges (`.ignoreFieldBridge()`) like in Search 5.
* And more!

=== Easier to use, safer automatic indexing

Automatic indexing improvements are not limited to bridges:
`@IndexedEmbedded` is easier to configure properly in Search 6, too.

To be precise, changes on indexed-embedded entities trigger reindexing of the "embedding" entity automatically,
and annotating the inverse side of the association with `@ContainedIn` is no longer needed in most cases.
A mapping error will be reported when the inverse side of the association cannot be resolved.

[[runtime-joins]]
=== Runtime joins

Hibernate Search 6.0 introduces "nested" fields and predicates,
similar to the feature with the same name in Elasticsearch.

See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-indexedembedded-storage[`@IndexedEmbedded` storage type]
in the reference documentation.
