:awestruct-layout: project-releases-series
:awestruct-project: search
:awestruct-series_version: "6.0"

[[preview-status]]
=== Preview status

Hibernate Search 6.0 is currently a *technology preview* and is not ready for production.

While the core of Hibernate Search 6 is there, there are still a lot of limitations:

* Features are partially implemented or simply missing.
For example, you cannot index a `Double` property yet,
you cannot configure custom Lucene directories,
you cannot ignore bridges in the predicate DSL,
and so on.
* APIs are not considered stable yet.
* The low-level parts of the Lucene backend from Hibernate Search 5
that improve its efficiency haven't been ported to Hibernate Search 6 yet.
This results in obvious performance bottlenecks,
such as all the indexing works from a multi-threaded application being executed
one after another and without any form of batching.

The exact features that are currently implemented and expected to work will be added to the reference documentation
as new Alpha versions are released, but to sum up, here is what you can start to play with:

* ORM integration:
** Mapping of entities using either annotation mapping or programmatic mapping.
However, we do not offer all the options that were available in Search 5 (yet),
and we do not support all the data types (yet).
** Automatic indexing of ORM entities as they are persisted within a transaction
(enabled automatically if Hibernate Search is in your classpath and the entity is mapped).
** Mass indexing of ORM entities that are already persisted in database.
** Search for ORM entities using their Hibernate Search index,
and retrieving managed entities as results.
However, we do not offer many options regarding how the entities are retrieved and initialized (yet).
** Custom, user-defined type bridges, property bridges or value bridges.
However, the API to retrieve information from POJOs is currently quite cumbersome:
we know that and will work on a lighter API
(see https://hibernate.atlassian.net/browse/HSEARCH-3297[HSEARCH-3297],
https://hibernate.atlassian.net/browse/HSEARCH-3298[HSEARCH-3298]).
* Search DSL
** All the predicates listed in `org.hibernate.search.engine.search.dsl.predicate.SearchPredicateFactoryContext`.
However, we do not offer all the options that were available in Search 5 (yet).
** All the sorts listed in `org.hibernate.search.engine.search.dsl.sort.SearchSortContainerContext`.
However, we do not offer all the options that were available in Search 5 (yet).
** All the projections listed in `org.hibernate.search.engine.search.dsl.projection.SearchProjectionFactoryContext`.

[[orm-version]]
=== ORM version

Hibernate Search 6 still relies on ORM 5.4 at the moment,
because it requires features that are not yet implemented in ORM 6 (still in development).

[[lucene-7]]
=== Lucene 7

The Lucene backend now uses Lucene 7.6.

[[elasticsearch-6]]
=== Elasticsearch 6

The Elasticsearch backend now works with Elasticsearch 5.6 or 6.6.
Support for older versions of Elasticsearch was dropped.

[[api-refresh]]
=== API refresh

A lot of APIs have been changed, for multiple reasons.

==== No more Lucene in Hibernate Search APIs

Hibernate Search APIs now abstract from the Lucene APIs,
so that alternative backends such as Elasticsearch can be used without having Lucene on your classpath.

This should also allow us to upgrade the Lucene version more easily:
in Search 5, as Lucene was "part of" our APIs,
we were severely limited when we wanted to upgrade to a newer Lucene version,
because any breaking change in Lucene could mean a breaking change for our users, too.
Now that using Lucene APIs is no longer necessary to use Hibernate Search,
upgrades should be faster.

==== New Search DSL

The Search DSL is brand new, with several improvements:

* Ability to use lambdas for more concise query definition, even when queries are complex.
* Type-safe projections thanks to the brand new projection DSL.
* Injection of native predicates (`org.apache.lucene.search.Query`, JSON for Elasticsearch)
within DSL-created predicates.
This is not new for the Lucene integration, but it is for the Elasticsearch integration.
See `org.hibernate.search.engine.search.dsl.predicate.SearchPredicateFactoryContext.extension(SearchPredicateFactoryContextExtension<T>)`
`org.hibernate.search.backend.elasticsearch.ElasticsearchExtension.get()` and
`org.hibernate.search.backend.lucene.LuceneExtension.get()`.

[[bridge-2.0]]
==== Bridge 2.0

The bridge APIs had to change as part of the API refresh,
so we took this opportunity to overhaul bridge APIs to make bridges more powerful.

The new Bridge APIs are completely different, but with a lot of improvements:

* Custom (user-defined) bridge annotations, allowing to pass type-safe parameters, and not just strings.
* Better support for dirty checking optimization in bridges (in `TypeBridge` in particular),
by allowing bridges to declare what parts of the entity they use.
* Predicates on non-String fields will work without having to bypass bridges (`.ignoreFieldBridge()`) like in Search 5.
* And more!

=== Easier to use automatic indexing

Automatic indexing improvements are not limited to bridges:
`@IndexedEmbedded` is easier to configure properly in Search 6, too.

To be precise, changes on indexed-embedded entities trigger reindexing of the "embedding" entity automatically,
and annotating the inverse side of the association with `@ContainedIn` is no longer needed in most cases.
A mapping error will be reported when the inverse side of the association cannot be resolved.

[[runtime-joins]]
=== Runtime joins

Hibernate Search 6.0 introduces  "nested" fields and predicates,
similar to the feature with the same name in Elasticsearch.

See `org.hibernate.search.mapper.pojo.mapping.definition.annotation.IndexedEmbedded.storage`
and `org.hibernate.search.engine.search.dsl.predicate.SearchPredicateFactoryContext.nested()`.
