# not quite sure what node path means
# I set it up as a unique identifier
nodePath=/hibernateNoSQL
projectName=Hibernate NoSQL
homePage=https://hibernate.org/nosql/
license=ASL
description=Connectors and dialects for NoSQL databases on Hibernate ORM
specialIcon=hibernate
downloadsLink=https://hibernate.org/nosql/downloads/
docsLink=https://hibernate.org/nosql/documentation/
communityLink=https://hibernate.org/community/
knowledgeBaseLink=
userForumLink=https://discourse.hibernate.org/c/hibernate-nosql
devForumLink=
mailingListLink=https://lists.jboss.org/mailman/listinfo/hibernate-dev
chatLink=https://webchat.freenode.net/?channels=hibernate
blogLink=https://in.relation.to/
twitterLink=https://twitter.com/hibernate
srcLink=
anonymousLink=
committerLink=
fisheyeLink=
viewvcLink=
githubLink=https://github.com/hibernate/hibernate-nosql/
anonymousGitLink=
committerGitLink=
    
# Build links
#######################################################
buildLink=
hudsonLink=
    
# Issue tracker links
#######################################################
issueTrackerLink=
jiraLink=https://hibernate.atlassian.net/browse/HNSQL
