= Hibernate Validator roadmap
Hardy Ferentschik
:awestruct-layout: project-frame
:awestruct-project: validator
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Validator is community driven and as such the roadmap constantly evolves to reflect the
users needs.
You can find a fine grained roadmap in our https://hibernate.atlassian.net/browse/HV[issue tracker],
but this page is a good starting point to see where we are going.

== Hibernate Validator 6.0

Annotation processor improvements::
Taking into account new places where constraint annotations can be placed (https://hibernate.atlassian.net/browse/HV-879[HV-879]) +
Taking into account XML configuration (https://hibernate.atlassian.net/browse/HV-308[HV-308])

Misc::
Usage of lambdas in the programmatic API (https://hibernate.atlassian.net/browse/HV-947[HV-947]) +
Explore message interpolator receiving multiple locales (https://hibernate.atlassian.net/browse/HV-1436[HV-1436]) +
Explore ability to validate an object and a list of changes (https://hibernate.atlassian.net/browse/BVAL-214[BVAL-214]) +
Integration with JavaFX (https://hibernate.atlassian.net/browse/HV-653[HV-653]) +
Introduce mechanism to order constraints (https://hibernate.atlassian.net/browse/HV-462[HV-462]) +
Better integration with ORM, especially DDL constraint generation (https://hibernate.atlassian.net/browse/HV-830[HV-830])

Internal::
Provide ability to retrieve metadata from Jandex index (https://hibernate.atlassian.net/browse/HV-644[HV-644]) +
Further unification of bean and method validation (https://hibernate.atlassian.net/browse/HV-467[HV-467]) +
Usage of method handles for accessing bean state (https://hibernate.atlassian.net/browse/HV-1226[HV-1226])
