= Roadmap
Hardy Ferentschik
:awestruct-layout: project-standard
:awestruct-project: validator
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Validator is community driven and as such the roadmap constantly evolves to reflect the
users needs.
You can find a fine grained roadmap in our https://hibernate.atlassian.net/browse/HV[issue tracker],
but this page is a good starting point to see where we are going.

== Hibernate Validator 5.3

OSGi::
Expose Validator as OSGi service (https://hibernate.atlassian.net/browse/HV-570[HV-570])

Annotation processor improvements::
Taking into account XML configuration (https://hibernate.atlassian.net/browse/HV-308[HV-308]) +
Verify group sequences (https://hibernate.atlassian.net/browse/HV-455[HV-455]) +
Verify the validity of constraint declarations (e.g. min < max for @Size) (https://hibernate.atlassian.net/browse/HV-270[HV-270])

Misc::
Integration with JavaFX (https://hibernate.atlassian.net/browse/HV-653[HV-653]) +
Introduce mechanism to order constraints (https://hibernate.atlassian.net/browse/HV-462[HV-462]) +
Better integration with ORM, especially DDL constraint generation (https://hibernate.atlassian.net/browse/HV-830[HV-830]) +
New range of Hibernate Validator specific constraints and potential dedicated
constraint module (https://hibernate.atlassian.net/browse/HV-553[HV-553]) +
Create standalone method interceptor using Byteman (https://hibernate.atlassian.net/browse/HV-432[HV-432])

Internal::
Provide ability to retrieve metadata from Jandex index (https://hibernate.atlassian.net/browse/HV-644[HV-644]) +
Further unification of bean and method validation (https://hibernate.atlassian.net/browse/HV-467[HV-467]) +
Switch to Gradle as build tool (https://hibernate.atlassian.net/browse/HV-641[HV-641])
