= Hibernate Validator roadmap
Hardy Ferentschik
:awestruct-layout: project-frame
:awestruct-project: validator
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Validator is community driven and as such the roadmap constantly evolves to reflect the
users needs and contributions.

You can find a fine grained roadmap in our https://hibernate.atlassian.net/browse/HV[issue tracker],
but this page is a good starting point to see where we are going.

== Hibernate Validator 6.0.x

Engine::
Explore message interpolators receiving several locales (https://hibernate.atlassian.net/browse/HV-1436[HV-1436]) +
Support custom field/getter selection strategy (https://hibernate.atlassian.net/browse/HV-1363[HV-1363])

Annotation processor improvements::
Taking into account new places where constraint annotations can be placed (https://hibernate.atlassian.net/browse/HV-879[HV-879]) +
Taking into account XML configuration (https://hibernate.atlassian.net/browse/HV-308[HV-308])

== Hibernate Validator 6.1

Engine::
Explore taking some distance from the reflection API (e.g. dealing with `Type` is rather confusing, replace some of the types with memory-friendly counterparts (`Method`?), do not rely on `TypeVariable`). Note that it might also help with the future usage of Jandex for annotation discovery.

Programmatic API::
Be able to define constraint on properties using lambdas (ie without constraint annotations)

Java 9::
Usage of method handles for accessing bean states (https://hibernate.atlassian.net/browse/HV-1226[HV-1226])

== Future versions

Engine::
Explore the ability to validate an object and a list of changes (https://hibernate.atlassian.net/browse/BVAL-214[BVAL-214]) +
Explore the usage of Jandex to build the metadata (https://hibernate.atlassian.net/browse/HV-644[HV-644])

