= Roadmap
Hardy Ferentschik
:awestruct-layout: project-roadmap
:awestruct-project: validator
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate Validator is community driven and as such the roadmap constantly evolves to reflect the
users needs and contributions.

You can find a fine grained roadmap in our https://hibernate.atlassian.net/browse/HV[issue tracker],
but this page is a good starting point to see where we are going.

== Hibernate Validator 6.0.x

Engine::
Explore message interpolators receiving several locales (https://hibernate.atlassian.net/browse/HV-1436[HV-1436]) +
Support custom field/getter selection strategy (https://hibernate.atlassian.net/browse/HV-1363[HV-1363]) +
Improve the performances and reduce the memory footprint

Annotation processor improvements::
Taking into account new places where constraint annotations can be placed (https://hibernate.atlassian.net/browse/HV-879[HV-879]) +
Taking into account XML configuration (https://hibernate.atlassian.net/browse/HV-308[HV-308])

== Hibernate Validator 6.1

Engine::
Explore taking some distance from the reflection API (e.g. dealing with `Type` is rather confusing, replace some of the types with memory-friendly counterparts (`Method`?), do not rely on `TypeVariable`). Note that it might also help with the future usage of Jandex for annotation discovery. +
Provide an SPI for making the retrieval of bean properties more flexible, allowing to support models not following the JavaBeans conventions, e.g. types generated by http://immutables.io[Immutables] which will use `property()` instead of `getProperty()`

Remote API::
Provide an HTTP endpoint which allows to validate single properties and also exposes constraint metadata via JSON (https://hibernate.atlassian.net/browse/HV-1500[HV-1500]). Web applications can integrate that endpoint to allow client-side validation of their models.

Programmatic API::
Be able to define constraint on properties using lambdas (ie without constraint annotations)

Java 9::
Usage of method handles for accessing bean states (https://hibernate.atlassian.net/browse/HV-1226[HV-1226]) +
Explore usage of http://download.java.net/java/jdk9/docs/api/java/util/spi/ResourceBundleProvider.html[ResourceBundleProvider] for obtaining validation error messages from other modules +
Providing Hibernate Validator with JDK 9 module descriptors

== Future versions

Engine::
Explore the ability to validate an object and a list of changes (https://hibernate.atlassian.net/browse/BVAL-214[BVAL-214]) +
Explore support for constraint ordering (http://beanvalidation.org/proposals/BVAL-248/[BVAL-248]) +
Explore support for other models than JavaBeans (https://hibernate.atlassian.net/browse/HV-1000[HV-1000]) +
Explore the usage of https://github.com/wildfly/jandex[Jandex] (a Java annotation indexer and offline reflection library) to build the metadata (https://hibernate.atlassian.net/browse/HV-644[HV-644])

