= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero, Yoann Rodière
:awestruct-layout: project-standard
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.10
:from_version_short: 5.9
:reference_version_full: 5.10.0.Final

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Hibernate Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

This version of Hibernate Search now requires using Hibernate ORM versions from the `5.3.x` family.

This implies it now requires *JPA 2.2*, as that's the base requirement for all Hibernate ORM 5.3 versions.

=== Configuration changes

The configuration properties didn't change.

=== API changes

* `ElasticsearchEnvironment.ANALYSIS_DEFINITION_PROVIDER` now contains the string
`"elasticsearch.analysis_definition_provider"` instead of `"hibernate.search.elasticsearch.analysis_definition_provider"`:
we removed the prefix to make this constant consistent with other constants in the same class.
* `org.hibernate.search.filter.FilterCachingStrategy#getCachedFilter(FilterKey)`
now has a default implementation for technical reasons,
but **it should always be overridden**.
* We added automatic https://en.wikipedia.org/wiki/Java_Platform_Module_System[JPMS module] names to our JARs.
Note that Hibernate Search JARs still can only be used as automatic modules,
because some of our dependencies cannot easily be used as modules yet.
Here are the module names:
** `org.hibernate.search.engine`
** `org.hibernate.search.orm`
** `org.hibernate.search.backend.elasticsearch`
** `org.hibernate.search.backend.elasticsearch.aws`
** `org.hibernate.search.clustering.jms`
** `org.hibernate.search.clustering.jgroups`
** `org.hibernate.search.jsr352.core`
** `org.hibernate.search.jsr352.jberet`
** `org.hibernate.search.serialization.avro`

=== SPI changes

* `org.hibernate.search.indexes.spi.IndexManagerType` now only has one method, `createIndexFamily`.
For an example of how to implement `IndexManagerType`, see commit
https://github.com/hibernate/hibernate-search/commit/22412acdb2d2f409ad24effa3d69e71e7bb92554[22412acdb2d2f409ad24effa3d69e71e7bb92554],
`ElasticsearchIndexManagerType` in particular.
* `org.hibernate.search.engine.service.beanresolver.spi.BeanResolver` now implements `Stoppable`.
* `org.hibernate.search.hcore.spi.BeanResolver` has been removed.
Use the `org.hibernate.resource.beans.container.spi.BeanContainer` concept native to Hibernate ORM instead;
Hibernate Search will automatically wire into whichever bean container is used in Hibernate ORM.
* `org.hibernate.search.hcore.spi.EnvironmentSynchronizer` now has an additional `whenEnvironmentDestroying(Runnable)` method.

=== Behavior changes

* As of https://hibernate.atlassian.net/browse/HSEARCH-3039[HSEARCH-3039],
Embedded IDs are no longer analyzed.
Embedded IDs are properties defined as `@DocumentId` (or, lacking that, JPA's `@Id`),
then embedded in another document using `@IndexedEmbedded(includeEmbeddedObjectId = true)`
or `@IndexedEmbedded(includePaths = { ..., "<the ID property name>", ... })`.
