= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero, Yoann Rodière
:awestruct-layout: project-standard
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.10
:from_version_short: 5.9
:reference_version_full: 5.10.7.Final

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Hibernate Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

This version of Hibernate Search now requires using Hibernate ORM versions from the `5.3.x` family.

This implies it now requires *JPA 2.2*, as that's the version of JPA implemented by Hibernate ORM 5.3.

=== Configuration changes

* We http://hibernate.org/search/releases/5.10/#jpms-automatic-module-names[added Java module names to our JARs].
The JVM was previously deriving the names from the JAR file names,
as it does with all JARs where no module name is defined.
If you have dependencies to Hibernate Search in your `module-info`,
you might need to update these dependencies.

=== API changes

* `ElasticsearchEnvironment.ANALYSIS_DEFINITION_PROVIDER` now contains `elasticsearch.analysis_definition_provider`,
without the `hibernate.search.` prefix, consistently with other constants in the same class.
* Binary compatibility with Hibernate Search 5.5 has been restored
in the few places of our API that had changed in incompatible way.
This is mainly of interest to Hibernate Search integrators.

=== SPI changes

* Two methods have been removed from `org.hibernate.search.indexes.spi.IndexManagerType`:
`createAnalyzerStrategy` and `createMissingValueStrategy`.
To replace them, we added `IndexFamilyImplementor createIndexFamily(ServiceManager, SearchConfiguration)`,
which creates an intermediary "index family" which in turns provides the analyzer strategy and missing value strategy.
See the javadoc for `org.hibernate.search.indexes.spi.IndexFamilyImplementor` for more information.
* `org.hibernate.search.hcore.spi.EnvironmentSynchronizer` now exposes a
`org.hibernate.search.hcore.spi.EnvironmentSynchronizer#whenEnvironmentDestroying` method.

=== Behavior changes

* As of https://hibernate.atlassian.net/browse/HSEARCH-3039[HSEARCH-3039],
Embedded IDs are no longer analyzed.
Embedded IDs are properties defined as `@DocumentId` (or, lacking that, JPA's `@Id`),
then embedded in another document using `@IndexedEmbedded(includeEmbeddedObjectId = true)`
or `@IndexedEmbedded(includePaths = { ..., "<the ID property name>", ... })`.
