= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero, Yoann Rodière
:awestruct-layout: project-standard
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.11
:from_version_short: 5.10
:reference_version_full: 5.11.6.Final

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Hibernate Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

This version of Hibernate Search now requires using Hibernate ORM versions from the `5.4.x` family.

=== Configuration changes

The configuration properties didn't change.

=== API changes

The APIs didn't change.

=== SPI changes

The SPIs didn't change.

=== Behavior changes

No behavior changes to report.
