= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero
:awestruct-layout: project-standard
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.3
:from_version_short: 5.2
:reference_version_full: 5.3.0.Final

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

The basic requirements didn't change.

=== API changes

==== The Faceting API and engine

The Faceting engine has seen significant improvements.
Most of the changes don't affect the API, with two very notable exceptions:

1. You have to add a `@Facet` (or `@Facets`) annotation on the fields which you intend to use for faceting.
2. The maximum number of facets returned by a query is now 100 by default.
You can override this to a value of your own by calling `.maxFacetCount( <value> )` when building the faceting request.

A full explanation and examples can be found on the http://in.relation.to/Bloggers/HibernateSearch530Beta1WithNativeLuceneFaceting[this blog post].
