= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero, Gunnar Morling
:awestruct-layout: project-frame
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.6
:from_version_short: 5.5
:reference_version_full: 5.6.0.Alpha3

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

This version of Hibernate Search now requires using *Apache Lucene 5.5.0*.

=== API changes

A new method `getShardIdentifiersForDeletion()` has been added to `org.hibernate.search.store.ShardIdentifierProvider` (https://hibernate.atlassian.net/browse/HSEARCH-2075[HSEARCH-2075]).
Existing implementations which are not derived from `ShardIdentifierProviderTemplate` need to be adapted.

This release of Hibernate Search upgrades the dependency to Lucene from 5.3.1 to 5.5.0.
In case you are working with Lucene types directly, thus also check out the Apache Lucene 5 http://lucene.apache.org/core/5_5_0/MIGRATE.html[migration guide] as well as the Apache Lucene http://lucene.apache.org/core/5_4_0/changes/Changes.html[5.4] and http://lucene.apache.org/core/5_5_0/changes/Changes.html[5.5] change logs.

=== SPI changes

A new method `flushAndReleaseResources()` has been added `org.hibernate.search.indexes.spi.IndexManager`.
Existing implementations need to be adjusted.

A new method `flushAndReleaseResources()` has been added to `org.hibernate.search.backend.spi.BackendQueueProcessor`.
Existing implementations need to be adjusted, but we don't expect many such implementations in the wild.

The method `org.hibernate.search.backend.spi.BackendQueueProcessor#initialize()` has been changed to accept any kind of `IndexManager` now instead of `DirectoryBasedIndexManager`.
Existing implementations need to be adjusted, but we don't expect many such implementations in the wild.
