= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero, Gunnar Morling
:awestruct-layout: project-frame
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.7
:from_version_short: 5.6
:reference_version_full: 5.7.0.CR1

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

This version of Hibernate Search now requires using Hibernate ORM version `5.2.x`.

This implies it now requires Java SE version *8*.

=== API changes

There have been no relevant API changes within Hibernate Search itself; consider though that the new version of Hibernate ORM introduced some very minor changes in API,
especially as now `org.hibernate.Session` implements `javax.persistence.EntityManager` rather than requiring an adapter, as it did in previous versions.

