= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Sanne Grinovero, Yoann Rodière
:awestruct-layout: project-standard
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 5.9
:from_version_short: 5.8
:reference_version_full: 5.9.0.Final

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Hibernate Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating an existing application using any version `{from_version_short}.x` of Hibernate Search to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`. If you think something is missing or something does not work, please link:/community[contact us].

=== Requirements

The basic requirements didn't change.

=== Configuration changes

The configuration properties didn't change.

=== API changes

The APIs didn't change.

Note that new APIs were introduced as part of the link:/search/releases/5.9/#jsr352[JSR-352 integration].

=== SPI changes

 * `org.hibernate.search.backend.impl.jms.AbstractJMSHibernateSearchController` is now deprecated.
   implementors should extend `org.hibernate.search.backend.jms.spi.AbstractJMSHibernateSearchController` instead.
 * A new SPI, `org.hibernate.search.orm.spi.SearchIntegratorHelper`, allows to extract a `SearchIntegrator`
   from a `SessionFactory`.
   This should mainly be of use for implementors of `AbstractJMSHibernateSearchController`.
 * `org.hibernate.search.elasticsearch.spi.DigestSelfSigningCapable` has been removed.
   HTTP entities passed to the client now implement `writeTo(OutputStream)`,
   which can be called to retrieve and process the content of the entity.
