# not quite sure what node path means
# I set it up as a unique identifier
nodePath=/hibernateRepositories
projectName=Hibernate Data Repositories
homePage=http://hibernate.org/repositories/
license=LGPL
description=An implementation of Jakarta Data
specialIcon=hibernate
downloadsLink=http://hibernate.org/repositories/downloads/
docsLink=http://hibernate.org/repositories/documentation/
communityLink=http://hibernate.org/community/
knowledgeBaseLink=
userForumLink=https://discourse.hibernate.org/c/hibernate-orm
devForumLink=
mailingListLink=https://lists.jboss.org/mailman/listinfo/hibernate-dev
chatLink=http://webchat.freenode.net/?channels=hibernate
blogLink=https://in.relation.to/
twitterLink=http://twitter.com/hibernate
srcLink=
anonymousLink=
committerLink=
fisheyeLink=
viewvcLink=
githubLink=https://github.com/hibernate/hibernate-orm/
anonymousGitLink=
committerGitLink=
    
# Build links
#######################################################
buildLink=
hudsonLink=
    
# Issue tracker links
#######################################################
issueTrackerLink=https://github.com/hibernate/hibernate-reactive/issues
jiraLink=
