= Prove your skills using JPA with Hibernate
:awestruct-layout: project-standard
:awestruct-project: orm

== About the Red Hat Certificate of Expertise in Persistence Exam certification pass

http://www.redhat.com/training/certifications/jbcd-persistence/

The Red Hat® Certificate of Expertise in Persistence Exam credential demonstrates an individual's readiness for the real-world tasks associated with using the Java™ Persistence API (JPA) with JBoss Hibernate. The JPA is a Java programming language framework for managing relational data, and Hibernate is a high-performance object-relational persistence and query service that implements the JPA.

In preparation to earn the Red Hat Certificate of Expertise in Persistence, Red Hat recommends the following:

=== Objectives

Red Hat Certificate of Expertise in Persistence Exam objectives  

https://www.redhat.com/training/courses/ex297/examobjective

=== Training

Red Hat JBoss Hibernate Technology (JB297)

https://www.redhat.com/training/courses/jb297/

Other JBoss product related trainings

http://www.redhat.com/training/paths/jboss-middleware-2.html



=== JBoss Certified Developer Trial Exam  

http://www.redhat.com/resourcelibrary/articles/jboss-certified-developer-trial-exam


[TIP]
=====

Familiarize yourself with the tools, environment, and requirements of a hands-on, task-based Red Hat JBoss developer exam.
=====
