= Contribute
:awestruct-layout: project-standard
:awestruct-project: orm

Thanks for your interest! Hibernate ORM is an open source project and community.  Contributions, of any type or any 
scope, drive the project forward!  

There are lots of ways to become part of the community and contribute, not just writing/fixing code...


== Help Other Users

The link:/community/[community] page lists a few places for users to find help such as IRC and forums.  Not to mention
that users often look for help in other places such as StackOverflow or JBoss forums.  A great way to get involved in the
community is to share your knowledge with others who need it.


== Improve Documentation

An extension of helping other users is to contribute documentation.  Its the help that keeps on giving!  

Whether you simply fix a typo, re-word an unclear section or add a whole new section/topic, improving the documentation
helps everyone.


== Discuss Development

As the development team discusses design of new features or tries to prioritize work it is great to have input from 
users.  As the saying goes, it is better to measure twice and cut once; and the more eyes we have on theses designs 
and the more voices in the discussions, the better measurements we get.  The best places to get involved in 
discussing development are the https://hibernate.hipchat.com/chat/room/1238636[ORM dev] HipChat channel, the #hibernate-dev IRC channel and the hibernate-dev mailing list.  

_Note: the #hibernate-dev IRC channel is visited very infrequently.  Prefer HipChat for real-time chat_


== Report/Investigate Bugs

Trying out releases and reporting/fixing problems is in many ways the cornerstone of open source development.  It is 
especially critical in the case of early releases (Alphas and Betas) as we are trying to solidify APIs and contracts.

When creating a bug report, please have a test case available that can be 1.) used to reproduce the issue and 2.)
used as a long-term regression test.
Please see https://github.com/hibernate/hibernate-test-case-templates[Hibernate Test Case Templates] for an easy
way to start!

Even if you cannot help code the fix for a bug, submitting test cases for reported 
https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HHH%20AND%20status%20%3D%20%22Awaiting%20Test%20Case%22[bugs that did not provide tests] 
is a great help get these bugs resolved.

Speaking of JIRA, helping us identify issues that duplicate other issues or that are out of date is a great help as well.  And voting
for issues that are important to you is important in terms of how the development team sets priorities.


== Contribute code

Details on contribiuting code (and documentation) are covered in the CONTRIBUTING.md file available in the repository's root directory (https://github.com/hibernate/hibernate-orm/blob/master/CONTRIBUTING.md).

Details on building the project are covered in the README.md file also available in the repository's root directory (https://github.com/hibernate/hibernate-orm/blob/master/README.md).

[NOTE]
====
CONTRIBUTING.md covers all branches.  README.md is specific to each branch, as it contains building information that varies based on the branch's `javac` requirements, build tool (Gradle, Maven, Ant), etc.
====
