:awestruct-layout: project-releases-series
:awestruct-project: search
:awestruct-series_version: "6.1"
:page-interpolate: true
:hsearch-doc-url-prefix: #{reference_doc(site.projects[page.project], series(page, page.series_version)).html_url}

=== Dependency upgrades

[[orm-version]]
Hibernate ORM::
Hibernate Search 6.1 is compatible with Hibernate ORM 5.6,
but also with Hibernate ORM 6.0 or 6.1 <<orm6,through separate Maven artifacts>>.

[[lucene-version]]Lucene::
The Lucene backend now uses Lucene 8.11.

[[elasticsearch-version]]
Elasticsearch::
The Elasticsearch backend now works with Elasticsearch 5.6, 6.8, 7.10 or 7.16.

[[async-indexing]]
=== Asynchronous, distributed automatic indexing

While it's technically possible to use Hibernate Search 6.0 and Elasticsearch in distributed applications,
it suffers from a few link:{hsearch-doc-url-prefix}#architecture-examples-no-coordination-elasticsearch-pros-and-cons[limitations].

The main goal of Hibernate Search 6.1 is to eliminate these limitations
by introducing coordination between application nodes
to implement asynchronous, distributed automatic indexing.

Hibernate Search 6.1 introduces the very first coordination strategy: `outbox-polling`.
This strategy creates an outbox table in the database to push entity change events to,
and relies on a background processor to consume these events and perform automatic indexing.

image::hsearch-architecture-outbox-polling-elasticsearch.svg[Clustered architecture with outbox polling and Elasticsearch backend,align="center",width="100%"]

Beside eliminating the limitations mentioned above,
another advantage of this strategy is that
Hibernate Search will no longer trigger lazy-loading or build documents in application threads,
which can improve the responsiveness of applications (less work to do on commit).

To learn more about an architecture based on `outbox-polling` coordination,
head to link:{hsearch-doc-url-prefix}#architecture-examples-outbox-polling-elasticsearch[this section of the documentation].
You can also get a quick overview of several architectures link:{hsearch-doc-url-prefix}#architecture-examples-overview[here].

To jump right in and try the strategy,
just set the following property
(you will also need to link:{hsearch-doc-url-prefix}#coordination-outbox-polling-schema[add tables to your database schema]):

[source]
----
hibernate.search.coordination.strategy = outbox-polling
----

Head to link:{hsearch-doc-url-prefix}#coordination-outbox-polling[this section of the documentation]
for more information on how to configure coordination.

[NOTE]
====
The `outbox-polling` coordination strategy can perfectly well be used with a Lucene backend.

You will still be limited to a single application node,
but you will benefit from all the other advantages (data safety, increased application responsiveness, ...).
====

[[opensearch]]
=== OpenSearch compatibility

Starting with version 6.1,
Hibernate Search is also compatible with https://opensearch.org/[OpenSearch],
the Apache 2.0 licensed fork of Elasticsearch,
and regularly tested against versions 1.0 and 1.2.

To use Hibernate Search with OpenSearch,
use the same Maven artifacts, configuration and API
that you would have used with Elasticsearch.

The only (minor) difference between using Elasticsearch and OpenSearch
is if you link:{hsearch-doc-url-prefix}#backend-elasticsearch-configuration-version[configure the Elasticsearch version explicitly]:
with OpenSearch, you need to prefix the version with `opensearch:`, e.g. `opensearch:1.0`.

[[search-dsl]]
=== Search DSL improvements

New link:{hsearch-doc-url-prefix}#search-dsl-predicate-terms[`terms` predicate]::
Matches documents for which a given field contains some terms, any or all of them.
+
Useful for enum-typed fields, in particular.
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.terms().field( "genre" )
                .matchingAny( Genre.CRIME_FICTION, Genre.SCIENCE_FICTION ) )
        .fetchHits( 20 );
----
New link:{hsearch-doc-url-prefix}#search-dsl-predicate-regexp[`regexp` predicate]::
Matches documents for which a given field contains a word matching the given regular expression.
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.regexp().field( "description" )
                .matching( "r.*t" ) )
        .fetchHits( 20 );
----
New link:{hsearch-doc-url-prefix}#_id_return_identifiers_of_matched_entities[`id` projection]::
Returns the identifier of the matched entity.
+
[source, JAVA, indent=0]
----
List<Integer> hits = searchSession.search( Book.class )
        .select( f -> f.id( Integer.class ) )
        .where( f -> f.matchAll() )
        .fetchHits( 20 );
----
link:{hsearch-doc-url-prefix}#search-dsl-sort-common-missing[Configurable `.missing()` behavior] for `distance` sort::
Distance sorts now allow
specifying the behavior when encountering documents with missing values
(though only `.missing().first()`/`.missing().last()` are supported with Elasticsearch).
+
[source, JAVA, indent=0]
----
GeoPoint center = GeoPoint.of( 47.506060, 2.473916 );
List<Author> hits = searchSession.search( Author.class )
        .where( f -> f.matchAll() )
        .sort( f -> f.distance( "placeOfBirth", center )
                .missing().first() )
        .fetchHits( 20 );
----
link:{hsearch-doc-url-prefix}#search-dsl-paths-relative[Relative field paths]::
The Search DSL now allows creating factories (`SearchPredicateFactory`, etc.)
that accept relative field paths.
+
This is mostly useful if you pass factories to reusable methods.
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.bool()
                .should( f.nested().objectField( "writers" )
                        .nest( matchFirstAndLastName(
                                f.withRoot( "writers" ),
                                "bob", "kane" ) ) )
                .should( f.nested().objectField( "artists" )
                        .nest( matchFirstAndLastName(
                                f.withRoot( "artists" ),
                                "bill", "finger" ) ) ) )
        .fetchHits( 20 );

private SearchPredicate matchFirstAndLastName(SearchPredicateFactory f,
        String firstName, String lastName) {
    return f.bool()
            .must( f.match().field( "firstName" )
                    .matching( firstName ) )
            .must( f.match().field( "lastName" )
                    .matching( lastName ) )
            .toPredicate();
}
----

[[mass-indexing-filter]]
=== Conditional mass indexing

Hibernate Search 6.1 introduces the ability
to link:{hsearch-doc-url-prefix}#mapper-orm-indexing-massindexer-conditional[apply the mass indexer to a subset of your entities],
based on an HQL/JPQL "where" clause.

[source, JAVA, indent=0]
----
SearchSession searchSession = Search.session( entityManager );
MassIndexer massIndexer = searchSession.massIndexer();
massIndexer.type( Book.class ).reindexOnly( "e.publicationYear <= 2100" );
massIndexer.type( Author.class ).reindexOnly( "e.birthDate < :birthDate" )
        .param( "birthDate", LocalDate.ofYearDay( 2100, 77 ) );
massIndexer.startAndWait();
----

[[named-predicates]]
=== Named predicates

Hibernate Search 6.1 adds link:{hsearch-doc-url-prefix}#mapper-orm-bridge-named-predicate[named predicates],
a way to define the search logic as part of a custom binder/bridge.

This is, in a way, the comeback of the
https://docs.jboss.org/hibernate/search/5.11/reference/en-US/html_single/#query-filter-fulltext["full-text filters" of Hibernate Search 5].

[[elasticsearch-custom-index-settings]]
=== Custom ES index settings

Starting with Hibernate Search 6.1,
you can link:{hsearch-doc-url-prefix}#_custom_index_settings[provide Hibernate Search with JSON files containing the desired settings of your indexes],
and Hibernate Search will automatically push these settings
when it creates/updates the indexes.

[[elasticsearch-custom-index-mapping]]
=== Custom ES index mapping

Starting with Hibernate Search 6.1,
you can link:{hsearch-doc-url-prefix}#_custom_index_mapping[provide Hibernate Search with JSON files containing part of the desired mapping of your indexes],
and Hibernate Search will automatically merge this mapping with the one it generated,
so that it gets pushed to Elasticsearch when it creates/updates the indexes.

This is especially useful to set top-level mapping attributes,
for example https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#disable-source-field[disabling the `_source` field].

[[lucene-reader]]
=== Access to Lucene's `IndexReader`

Starting with Hibernate Search 6.1, you can now link:{hsearch-doc-url-prefix}#_retrieving_a_lucene_indexreader[retrieve an `IndexReader`]
when using the Lucene backend:

[source, JAVA, indent=0]
----
SearchMapping mapping = Search.mapping( entityManagerFactory );
LuceneIndexScope indexScope = mapping
        .scope( Book.class ).extension( LuceneExtension.get() );
try ( IndexReader indexReader = indexScope.openIndexReader() ) {
    // work with the low-level index reader:
    numDocs = indexReader.numDocs();
}
----

While generally not necessary, this can be useful for advanced, low-level operations.

[[lucene-caching]]
=== Lucene low-level hit caching

Starting with version 6.1,
Hibernate Search allows
link:{hsearch-doc-url-prefix}#backend-lucene-search-caching[configuring the `QueryCache` and `QueryCachingPolicy`]
in the Lucene backend,
adding one more performance tweak for advanced Lucene users.

[[lucene-analyzer-definition-using-names]]
=== Lucene analyzer definition using tokenizer/filter names

Starting with Hibernate Search 6.1,
a `LuceneAnalysisConfigurer` can be implemented without referring to Lucene classes at all,
link:{hsearch-doc-url-prefix}#backend-lucene-analysis-analyzers-component-by-factory-name[referring to tokenizers and filters using their name]
instead.

This is useful in some modular environments where the application might have access to Hibernate Search classes,
but not to Lucene classes.

[[jakarta]]
=== Jakarta EE

Starting with Hibernate Search 6.1,
beside the traditional artifacts targeting Java EE (JPA, CDI, ...),
Hibernate Search now provides link:{hsearch-doc-url-prefix}#other-integrations-jakarta[alternative, experimental artifacts that target Jakarta EE 9.1]
(Jakarta Persistence 3, Jakarta CDI 3).

These artifacts have their artifact ID suffixed with "-jakarta",
similarly to the https://in.relation.to/2021/06/02/hibernate-orm-550-final-release/#getting-started-with-the-jakarta-jpa-api[equivalent artifacts for Hibernate ORM]
(which you should use together).

[NOTE]
====
The main artifacts (e.g. `org.hibernate.search:hibernate-search-mapper-orm`)
still target Java EE.
====

[[orm6]]
=== Hibernate ORM 6

Starting with Hibernate Search 6.1,
beside the traditional artifacts targeting Hibernate ORM 5.x,
Hibernate Search now provides link:{hsearch-doc-url-prefix}#other-integrations-orm6[alternative, experimental artifacts that target Hibernate ORM 6 and Jakarta EE 9.1]
(Jakarta Persistence 3, Jakarta CDI 3).

These artifacts have their artifact ID suffixed with "-orm6".

[NOTE]
====
The main artifacts (e.g. `org.hibernate.search:hibernate-search-mapper-orm`)
still target Hibernate ORM 5.x and Java EE.
====

[[java-modules]]
=== Java modules

Starting with version 6.1,
where possible,
Hibernate Search now provides multi-release JARs with a full https://www.oracle.com/corporate/features/understanding-java-9-modules.html[Java module definition]
that includes all the dependencies.

This excludes the Lucene backend in particular, because https://issues.apache.org/jira/browse/LUCENE-9499[Lucene 8 has split packages].
