:awestruct-layout: project-releases-series
:awestruct-project: search
:awestruct-series_version: "8.0"
:page-interpolate: true
:latest-release-version: #{series(page, page.series_version).releases.first.version}
:hsearch-doc-url-prefix: #{reference_doc(site.projects[page.project], series(page, page.series_version)).html_url}

****
[discrete]
=== Dependency upgrades

[[java-version]]
JDK::
Hibernate Search upgrades to JDK 17 as the baseline and drops JDK 11 compatibility.
[[orm-version]]
Hibernate ORM::
Hibernate Search now targets the Hibernate ORM 7.0 series, which implements Jakarta Persistence 3.2.0.
In particular, it is currently based on Hibernate ORM 7.0.0.CR1.
[[lucene-version]]
Lucene::
The Lucene backend now uses Lucene 9.12.1, while the `lucene-next` relies on Lucene 10.2.1
[[elasticsearch-version]]
Elasticsearch::
The Elasticsearch backend is compatible with Elasticsearch 8.16, 8.17, 8.18 and 9.0, as well as other already compatible versions.
[[opensearch-version]]
OpenSearch::
The Elasticsearch backend works with OpenSearch 2.17, 2.18, 2.19 and 3.0, as well as other already compatible versions.

[[metric-aggregations]]
[discrete]
=== Metric aggregations

The Hibernate Search DSL now allows requesting metric aggregations:

====
[source, Java, indent=0, subs="+attributes"]
----
AggregationKey<Double> avgPriceKey = AggregationKey.of( "avgPrice" ); // <1>
AggregationKey<LocalDate> oldestReleaseKey = AggregationKey.of( "oldestRelease" ); // <2>

SearchResult<Book> result = searchSession.search( Book.class )
    .where( f -> f.matchAll() )
    .aggregation( avgPriceKey, f -> f.avg().field( "price", Double.class ) ) // <3>
    .aggregation( oldestReleaseKey, f -> f.min().field( "releaseDate", LocalDate.class ) ) // <4>
    .fetch( 20 );

Double avgPrice = result.aggregation( avgPriceKey ); // <5>
LocalDate oldestRelease = result.aggregation( oldestReleaseKey );
----
<1> Create an aggregation key for an average price aggregation.
<2> Create an aggregation key for a minimum date aggregation.
<3> Request an `.avg()` aggregation on the price field.
Specifying `Double` here defines the expected return type of the computed aggregation.
<4> Request a `.min()` aggregation on the release date field.
Specifying `LocalDate` here defines the expected return type of the computed aggregation.
<5> Extract the aggregated value from the results.
====

See the corresponding section on link:{hsearch-doc-url-prefix}#search-dsl-aggregation-metric[metric aggregations]
to learn which aggregations are available.

[[backend-lucene-next]]
[discrete]
=== New Lucene backend

While Hibernate Search 8.0 still targets JDK 17, Lucene, starting with version 10,
is leveraging new Java APIs, particularly to work with memory, that are available starting with JDK 21.
To give users an option to work with the newer Lucene version, Hibernate Search introduces the
`hibernate-search-backend-lucene-next` backend.

Currently, this backend is backed by Lucene 10 and requires JDK 21. In terms of functionality,
both Lucene-based backends have the same search capabilities.

See link:{hsearch-doc-url-prefix}#other-integrations-lucene-next[this section] of the reference documentation
to learn more.

[[multi-collectors]]
[discrete]
=== Projecting multivalued fields

It is now possible to use other collection types than `List` for multivalued projections:

.Using a Set to collect author names in a projection constructor
====
[source, JAVA, indent=0, subs="+callouts"]
----
@ProjectionConstructor
public record MyBookProjection(
    @IdProjection Integer id,
    String title,
    Set<String> authors) {  // <1>
}
----
<1> Using `Set` as a collection for a multivalued projection.
====
.Using the set collector within projection DSL
====
[source, JAVA, indent=0, subs="+callouts"]
----
List<Set<String>> hits = searchSession.search( Book.class )
    .select( f -> f.field( "authors.lastName", String.class ).set() ) // <1>
    .where( f -> f.matchAll() )
    .fetchHits( 20 );
----
<1> Using the set collector.
====

Hibernate Search comes with implementation for most popular collections,
but it is also possible to extend it and use a custom collector for an unsupported collection:

====
[source, JAVA, indent=0, subs="+callouts"]
----
List<MyCustomCollection<String>> hits = searchSession.search( Book.class )
    .select( f -> f.field( "authors.lastName", String.class ).collector( new MyCustomCollector() ) ) // <1>
    .where( f -> f.matchAll() )
    .fetchHits( 20 );
----
<1> Pass an instance of `ProjectionCollector.Provider` to the `.collector()` method.
====

[[logging-categories]]
[discrete]
=== Logging categories

Hibernate Search now utilizes logging categories instead of FQCNs. It is now easier to enable logging
when debugging a particular area of Hibernate Search:

[source, properties, indent=0, subs="+callouts"]
----
# Set logging level for massindexing events to `TRACE`:
org.hibernate.search.mapper.massindexing=TRACE
----

See the corresponding section on link:{hsearch-doc-url-prefix}#logging-categories-aggregated[logging categories]
to find out which categories are available.

[[static-metamodel]]
[discrete]
=== Static metamodel

Hibernate Search's link:{hsearch-doc-url-prefix}#static-metamodel[static metamodel] is a set of generated classes that represents the structure of each entity's index,
thereby allowing type-safe references to index fields when creating search queries through the link:{hsearch-doc-url-prefix}#search-dsl[Search DSL].

The basic principles are very similar to the link:{horm-doc-url-prefix}#tooling-modelgen[JPA static metamodel available in Hibernate ORM],
but in the case of Search the metamodel is about indexes rather than entities.

To try out this new feature, add the annotation processor to the build configuration:

====
[source,XML,subs="+attributes"]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <executions>
        <execution>
            <id>default-compile</id>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>org.hibernate.search.processor.HibernateSearchProcessor</annotationProcessor> <1>
                </annotationProcessors>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.hibernate.search</groupId>
                        <artifactId>hibernate-search-processor</artifactId> <2>
                    </path>
                    <path>
                        <groupId>org.hibernate.search</groupId>
                        <artifactId>hibernate-search-backend-lucene</artifactId> <3>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </execution>
    </executions>
</plugin>
----

<1> Provide the fully qualified class name of the annotation processor that generates the metamodel.
<2> Add the `org.hibernate.search:hibernate-search-processor` dependency to the annotation processor path (a superset of the compile path),
so the Java compiler can find the processor.
<3> Add the backend dependency, in this example, the Lucene backend, to the annotation processor path.

NOTE: The version of both annotation processor and backend dependencies can be omitted in the definition of the annotation paths,
because they are defined in the Hibernate Search BOM, which we recommend you import via dependency management.
This way the generated metamodel classes will be based on the same backend that the application uses.
====

And then use the generated metamodel classes to create search queries, e.g.:

====
[source, JAVA, indent=0, subs="+callouts"]
----
SearchSession searchSession = /* ... */; // <1>
var scope = Book__.INDEX.scope( searchSession ); // <2>

List<Book> hits = searchSession.search( scope )
    .where( f -> f.match()
        .field( Book__.INDEX.title ).field( Book__.INDEX.description ) // <3>
        .matching( "robot" ) )
    .fetchHits( 20 );
----
<1> Obtain the search session.
<2> Create the search scope over the book index. Using such scope in the link:{hsearch-doc-url-prefix}#search-dsl[Search DSL] will automatically
limit acceptable field references to the ones obtained from the `Book__.INDEX`
<3> Use the metamodel to reference the fields when creating the queries.
====


See the corresponding section on link:{hsearch-doc-url-prefix}#static-metamodel[static metamodel]
to find out more.
****
