= Getting started with Hibernate ORM
:awestruct-layout: project-standard
:awestruct-project: orm
:toc:
:toc-placement: preamble
:page-interpolate: true
:latest_stable: #{latest_stable_release(page).version}

This page lists just the basic information needed to get up and running with the latest version of Hibernate ORM.

If you are approaching Hibernate for the first time, the http://docs.jboss.org/hibernate/orm/current/quickstart/html_single/[Getting Started Guide] is the best place to start.

More thorough information is presented in the https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html[User Guide].

== System Requirements

Hibernate 5.2 and later versions require at least Java 1.8 and JDBC 4.2.

Hibernate 5.1 and older versions require at least Java 1.6 and JDBC 4.0.

[TIP]
====
When building Hibernate 5.1 or older from sources, you need Java 1.7 due to a bug in the JDK 1.6 compiler.
====

== Dependency Management

It is highly recommended to consume Hibernate ORM artifacts through a dependency management tool.
The artifacts can be found in Maven's central repository but are released first in the
https://developer.jboss.org/wiki/MavenRepository[JBoss maven repository].

[NOTE]
====
Snapshots are only pushed to the JBoss snapshot repository,
so if you want to use SNAPSHOT versions be sure to add the https://repository.jboss.org/nexus/content/repositories/snapshots/org/hibernate/[JBoss snapshot repository] properly according to your build tool of choice.
====

The main Hibernate ORM artifact is named *hibernate-core*. If you want to use the Jakarta JPA APIs you can us the *hibernate-core-jakarta* artifact.

[TIP]
====
There are also a number of optional artifacts based on what specific features you wish to use.
These are discussed in the http://docs.jboss.org/hibernate/orm/current/quickstart/html_single/[Getting Started Guide].
====

To use Hibernate ORM in your own project you just need to name a dependency on it in your project.

[source,xml]
[subs="verbatim,attributes"]
.From Maven
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-core</artifactId>
   <version>{latest_stable}</version>
</dependency>
----

[source]
[subs="verbatim,attributes"]
.From Gradle
----
org.hibernate:hibernate-core:{latest_stable}
----

Or in case you want to use the Jakarta JPA API:

[source,xml]
[subs="verbatim,attributes"]
.From Maven
----
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-core-jakarta</artifactId>
    <version>{latest_stable}</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>3.0.0</version>
</dependency>
----

[source]
[subs="verbatim,attributes"]
.From Gradle
----
org.hibernate:hibernate-core-jakarta:{latest_stable}
org.glassfish.jaxb:jaxb-runtime:3.0.0
----

Note that you need a Jakarta XML Binding implementation when you want to use the Jakarta JPA version.
