= Getting started with Hibernate ORM
:awestruct-layout: project-frame
:awestruct-project: orm
:toc:
:toc-placement: preamble
:latest_stable: 4.2.7.SP1

== Building

For developers wanting to build from source, see the README.md file in the root of the project source.

== Contributing (pull requests)

For developers wanting to contribute back fixes/improvements, see the CONTRIBUTING.md file in the root of the project source.

== Using 

For developers wanting to use Hibernate ORM in their projects...

=== System Requirements

Hibernate ORM requires Java 6 or higher.

=== Via Maven Repository

The Hibernate ORM artifacts can be found in Maven's central repository but are released first in the JBoss maven repository. So it's not a requirement but we recommend to add this repository to your settings.xml file (see also Maven Getting Started for more details).

To use Hibernate ORM in your own project you just need to name a dependency on it in your project:

[source,xml]
[subs="verbatim,attributes"]
.From Maven
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-core</artifactId>
   <version>{latest_stable}</version>
</dependency>
----

From Gradle:

[source]
[subs="verbatim,attributes"]
.From Gradle
----
org.hibernate:hibernate-core:{latest_stable}
----

For projects using JPA, the artifact to reference is `hibernate-entitymanager` instead of `hibernate-core`.
