= Hibernate OGM roadmap
Davide D'Alto
:awestruct-layout: project-frame
:awestruct-project: ogm
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate OGM is young and community driven.
As such the roadmap constantly evolves to reflect the users needs.
You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/OGM[issue tracker]
but this page is a good and concise view of where we are going.
Dates are generally omitted, we release when we are ready.

== Hibernate OGM 4.0 Beta2

TODO: What has been added?

Basic JP-QL query support for Hibernate Search::
TODO: gunnar what is the list of supported features
Basic JP-QL query support for MongoDB::
TODO: gunnar what is the list of supported features
Discriminator based hierarchy::
Support for hierarchy of class using a discriminator column as defined by JPA.

== Hibernate OGM 4.0 Beta3

Native query::
Offer the ability to pass a native backend query and bind the result to an entity.
All flexibility of the native underlying query system is available
at the cost of portability.

Use immutable metadata info to lower memory pressure::
Data passed to the [classname]+GridDialect+ are made of:

* an object specific data (id etc)
* an object type generic data (table name, column name etc)

+
The object type information could be shared to lower memory consumption
and avoid the object creation cost.

== Hibernate OGM 4.0 Beta4

Annotation based option system::
Each datastore can use specific annotations to customize its behavior.
The user can use either annotations or a programmatic API

* offer ability for each dialect to react to metadata specific information
* programmatic and annotation based
* for different scopes: generic, type and properties
* retrofit this for MongoDB's options

== Hibernate OGM 4.0

Neo4J backend::
Support Neo4J with ability to keep node reference for cheap navigation when resolving proxies
thus avoiding unnecessary lookups.

* Store tuple as data snapshot via IdentityMap or enhanced entity
* Use stored tuples as navigation tools instead of fetching (graph databases)

Batch changes per transactions::
Offer the [classname]+GridDialect+ the option to receive a batch of operations
to execute. Some drivers are better that way
and can increase the isolation lever.



=== Additional query support

TODO: Gunnar, add the list of shortcut we took as todo to fix here +
TODO: what is missing feature wise?

== Hibernate OGM 4.1

Polyglot persistence::
Offer ability to store entities into different backends.
Exploration of Cassandra::
Implement the Cassandra datastore and its CQL query backend.
Exploration of HBase::
Implement the HBase datastore and its query support
Migrate to Hibernate ORM 5::
When Hibernate ORM 5 is out, look at migrating to the new codebase.
Offer per session and per statement option customization::
eg for a given call, influence the quorum factor
Set benchmark solution and coverage TCK with automated test::
Start exploring benchmark solution with regular tests in a CI.
Add reusable TCK for both CRUD and query support.
Custom types::
Offer custom types like Hibernate ORM's user type.

== Hibernate OGM 4.2

Use Teiid query engine for joins and aggregation::
Explore reuse of Teiid query engine for smarter queries
General NoSQL and query depth and breath improvements::
Continue mapping of query engine on other NoSQL
Continue converage of breath of supported queries
Map/Reduce on queries::
Map/Reduce based resolution of subgraphs of a query
Infinispan over HotRod::
Support non library mode for Infinispan
