= Roadmap
Davide D'Alto
:awestruct-layout: project-roadmap
:awestruct-project: ogm
:toc:
:toc-placement: preamble
:toc-title: Releases

Hibernate OGM is community driven.
As such the roadmap constantly evolves to reflect the users needs.
You can find a finer grained roadmap in our https://hibernate.atlassian.net/browse/OGM[issue tracker]
but this page is a good and concise view of where we are going.
Dates are generally omitted, we release when we are ready.

== Hibernate OGM 5.4

Core::
Upgrade to Hibernate ORM 5.3, JPA 2.2 +
Upgrade to Hibernate Search 5.10 +
Support for WildFly 13

Infinispan::
Upgrade to Infinispan 9.4 +
Initial support for remote JPQL queries +
Simplify configuration of new caches +
Support calls to server side tasks

Neo4j::
Creation of indexes +
Support positional parameters with native Cypher queries +
Support calls to remote procedures 

MongoDB::
Support calls to server side JavaScript +
Drop a collection using native queries +
Support for GridFS

== Hibernate OGM Next

Mapping strategies::
Rethink the default values for the mapping approaches after more user feedback.
A backward compatible mode will be kept however.

Custom types::
Offer custom types like Hibernate ORM's user type.

Offer per session and per statement option customization::
e.g. for a given call, influence the quorum factor

General NoSQL and query depth and breath improvements::
Continue mapping of query engine on other NoSQL +
Continue coverage of breath of supported queries

Denormalization engine::
Offer ability to store data in different structures denormalized. +
Let loading and queries use these denormalized versions for faster retrieval. +
The goal is to offer a declarative approach
instead of the imperative approach used usually in the NoSQL land.

Migration engine::
Offer options to support transparent migrations when (non)schema has migrated.
Annotation based or API based. +
For example, one would rename a property from a to b,
the migration engine will know that, read the old value if present,
and migrate to the new schema.

Polyglot persistence::
Offer ability to store entities into different backends.
Entities could be in either backends.

Write-behind cross-backends::
Offer ability to store into two backends.
In particular, store data in a NoSQL backend and a relational database.
