# Default page title
title: Hibernate

# Project id name
project: hibernate

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

maven:
  central_base_url: 'https://repo.maven.apache.org/maven2/'
  jboss_nexus_base_url: 'https://repository.jboss.org/nexus/content/repositories/public/'

# project specific information
projects:
  ##################################################################################################
  # ORM
  ##################################################################################################
  orm:
    name: Hibernate ORM
    icon: 'icon-table'
    sourceforge_url: http://sourceforge.net/projects/hibernate/files/hibernate-orm/
    zip_file: hibernate-release-VERSION.zip
    maven:
      group_id: org.hibernate
      main_artifact_id: hibernate-core
      nexus_search:
        group_id_pattern: org.hibernate
        artifact_id_pattern: hibernate-*
    reference_doc_prefix_url: https://docs.jboss.org/hibernate/orm/
    stable_reference_doc_prefix_url: https://docs.jboss.org/hibernate/stable/orm/
    reference_doc_path: userguide/html_single/Hibernate_User_Guide.html
    reference_pdf:
    javadoc_path: javadocs
    getting_started: /orm/documentation/getting-started
    blog_tag: Hibernate ORM
    blog_tag_url: hibernate-orm
    license:
      name: LGPL V2.1
      url: http://hibernate.org/license/
    jira:
      key: HHH
    integrations:
      java:
        name: Java
        url: http://www.oracle.com/technetwork/java/javase/downloads/index.html
      jpa:
        name: JPA
        url: http://www.oracle.com/technetwork/java/javaee/tech/persistence-jsp-140049.html
    menu:
      intern:
        - name: About
          href: '/orm/'
          css_class: 'home'
        - name: Releases
          href: '/orm/releases/'
          css_class: 'tags'
          releases_submenu: true
        - name: Documentation
          href: '/orm/documentation/'
          css_class: 'folder open'
        - name: Books
          href: '/orm/books/'
          css_class: 'book'
        - name: Migration guides
          href: 'https://github.com/hibernate/hibernate-orm/wiki/Migration-Guides'
          css_class: 'circle arrow up'
        - name: Roadmap
          href: 'https://github.com/hibernate/hibernate-orm/wiki/Roadmap'
          css_class: 'road'
        - name: Tooling
          href: '/orm/tooling/'
          css_class: 'wrench'
        - name: Envers
          href: '/orm/envers/'
          css_class: 'time'
        - name: Contribute
          href: '/orm/contribute/'
          css_class: 'users'
        - name: Paid support
          href: '/orm/support/'
          css_class: 'doctor'
        - name: Get Certified
          href: '/orm/certification/'
          css_class: 'certificate'
        - name: FAQ
          href: '/orm/faq/'
          css_class: 'help circle'
      extern:
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-orm'
          css_class: 'code'
        - name: Issue tracker
          href: 'https://hibernate.atlassian.net/browse/HHH'
          css_class: 'bug'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'comments'
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate'
          css_class: 'edit'
        - name: CI
          href: 'http://ci.hibernate.org/'
          css_class: 'treatment'

  ##################################################################################################
  # Search
  ##################################################################################################
  search:
    name: Hibernate Search
    icon: 'icon-search'
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-search/
    zip_file: hibernate-search-VERSION-dist.zip
    maven:
      group_id: org.hibernate
      main_artifact_id: hibernate-search-orm
      nexus_search:
        group_id_pattern: org.hibernate
        artifact_id_pattern: hibernate-search-*
    reference_doc_prefix_url: https://docs.jboss.org/hibernate/search/
    stable_reference_doc_prefix_url: https://docs.jboss.org/hibernate/stable/search/
    reference_doc_path: reference/en-US/html_single/
    reference_doc_pdf_path: reference/en-US/pdf/hibernate_search_reference.pdf
    javadoc_path: api
    getting_started: /search/documentation/getting-started
    blog_tag: Hibernate Search
    blog_tag_url: hibernate-search
    license:
      name: LGPL v2.1
      url: https://raw.github.com/hibernate/hibernate-search/master/lgpl.txt
    jira:
      key: HSEARCH
    integrations:
      java:
        name: Java
        url: http://www.oracle.com/technetwork/java/javase/downloads/index.html
      orm:
        name: Hibernate ORM
        url: /orm/
      lucene:
        name: Apache Lucene
        url: https://lucene.apache.org/core/
      elasticsearch:
        name: Elasticsearch
        url: https://www.elastic.co/products/elasticsearch
    menu:
      intern:
        - name: About
          href: '/search/'
          css_class: 'home'
        - name: Releases
          href: '/search/releases/'
          css_class: 'tags'
          releases_submenu: true
        - name: Documentation
          href: '/search/documentation/'
          css_class: 'book'
        - name: Roadmap
          href: '/search/roadmap/'
          css_class: 'road'
        - name: Contribute
          href: '/search/contribute/'
          css_class: 'users'
        - name: Tooling
          href: '/search/tooling/'
          css_class: 'wrench'
        - name: Paid support
          href: '/search/support/'
          css_class: 'doctor'
        - name: FAQ
          href: '/search/faq/'
          css_class: 'circle help'
      extern:
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-search'
          css_class: 'code'
        - name: Issue tracker
          href: 'https://hibernate.atlassian.net/browse/HSEARCH'
          css_class: 'bug'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'lock'
        - name: Forum
          href: 'https://forum.hibernate.org/viewforum.php?f=9'
          css_class: 'comments'
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/search'
          css_class: 'edit'
        - name: CI
          href: 'http://ci.hibernate.org/job/hibernate-search-master/'
          css_class: 'treatment'

  ##################################################################################################
  # Tools
  ##################################################################################################
  tools:
    name: Hibernate Tools
    icon: 'icon-wrench'
    blog_tag: JBoss Tools
    blog_tag_url: jboss-tools
    license:
      name: LGPL v2.1
      url: https://github.com/hibernate/hibernate-tools/blob/master/lgpl.txt
    menu:
      intern:
        - name: About
          href: '/tools/'
          css_class: 'home'
      extern:
        - name: Downloads
          href: 'http://www.jboss.org/tools/download/'
          css_class: 'cloud download'
        - name: Documentation
          href: 'http://www.jboss.org/tools/docs/'
          css_class: 'book'
          #TODO add FAQ, Roadmap and Contribute page
          #- name: FAQ
          #  href: '/search/faq/'
          #  css_class: 'circle help'
          #- name: Roadmap
          #  href: '/search/roadmap/'
          #  css_class: 'road'
          #- name: Contribute
          #  href: '/search/contribute/'
          #  css_class: 'users'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-tools'
          css_class: 'code'
        - name: Issue tracker
          href: 'https://hibernate.atlassian.net/browse/HBX'
          css_class: 'bug'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'comments'
        - name: Wiki
          href: 'https://community.jboss.org/en/tools'
          css_class: 'edit'
        - name: CI
          href: 'http://hudson.jboss.org/hudson/job/hibernate-tools-trunk/'
          css_class: 'treatment'

  ##################################################################################################
  # Validator
  ##################################################################################################
  validator:
    name: Hibernate Validator
    icon: 'icon-check'
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-validator/
    zip_file: hibernate-validator-VERSION-dist.zip
    maven:
      group_id: org.hibernate.validator
      main_artifact_id: hibernate-validator
      nexus_search:
        group_id_pattern: org.hibernate*
        artifact_id_pattern: hibernate-validator*
    reference_doc_prefix_url: https://docs.jboss.org/hibernate/validator/
    stable_reference_doc_prefix_url: https://docs.jboss.org/hibernate/stable/validator/
    reference_doc_path: reference/en-US/html_single/
    reference_doc_pdf_path: reference/en-US/pdf/hibernate_validator_reference.pdf
    javadoc_path: api
    getting_started: /validator/documentation/getting-started
    blog_tag: Hibernate Validator
    blog_tag_url: hibernate-validator
    license:
      name: ASL v2
      url: https://raw.github.com/hibernate/hibernate-validator/master/license.txt
    jira:
      key: HV
    integrations:
      java:
        name: Java
        url: http://www.oracle.com/technetwork/java/javase/downloads/index.html
      bv:
        name: Bean Validation
        url: http://beanvalidation.org/
    menu:
      intern:
        - name: About
          href: '/validator/'
          css_class: 'home'
        - name: Releases
          href: '/validator/releases/'
          css_class: 'tags'
          releases_submenu: true
        - name: Documentation
          href: '/validator/documentation/'
          css_class: 'book'
        - name: Roadmap
          href: '/validator/roadmap/'
          css_class: 'road'
        - name: Contribute
          href: '/validator/contribute/'
          css_class: 'users'
        - name: Tooling
          href: '/validator/tooling/'
          css_class: 'wrench'
        - name: Paid support
          href: '/validator/support/'
          css_class: 'doctor'
        - name: FAQ
          href: '/validator/faq/'
          css_class: 'circle help'
      extern:
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-validator'
          css_class: 'code'
        - name: Issue tracker
          href: 'https://hibernate.atlassian.net/browse/HV'
          css_class: 'bug'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'comments'
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/validator'
          css_class: 'edit'
        - name: CI
          href: 'https://hibernate-validator.ci.cloudbees.com/'
          css_class: 'treatment'

  ##################################################################################################
  # OGM
  ##################################################################################################
  ogm:
    name: Hibernate OGM
    icon: 'icon-sitemap'
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-ogm/
    zip_file: hibernate-ogm-VERSION-dist.zip
    maven:
      group_id: org.hibernate.ogm
      main_artifact_id: hibernate-ogm-core
      nexus_search:
        group_id_pattern: org.hibernate.ogm
        artifact_id_pattern: hibernate-ogm-*
    reference_doc_prefix_url: https://docs.jboss.org/hibernate/ogm/
    stable_reference_doc_prefix_url: https://docs.jboss.org/hibernate/stable/ogm/
    reference_doc_path: reference/en-US/html_single/
    reference_doc_pdf_path: reference/en-US/pdf/hibernate_ogm_reference.pdf
    javadoc_path: api
    getting_started: /ogm/documentation/getting-started
    blog_tag: Hibernate OGM
    blog_tag_url: hibernate-ogm
    license:
      name: LGPL
      url: http://www.gnu.org/licenses/lgpl.html
    jira:
      key: OGM
    integrations:
      java:
        name: Java
        url: http://www.oracle.com/technetwork/java/javase/downloads/index.html
      jpa:
        name: JPA
        url: http://www.oracle.com/technetwork/java/javaee/tech/persistence-jsp-140049.html
      orm:
        name: Hibernate ORM
        url: /orm/
      search:
        name: Hibernate Search
        url: /search/
    menu:
      intern:
        - name: About
          href: '/ogm/'
          css_class: 'home'
        - name: Releases
          href: '/ogm/releases/'
          css_class: 'tags'
          releases_submenu: true
        - name: Documentation
          href: '/ogm/documentation/'
          css_class: 'book'
        - name: Roadmap
          href: '/ogm/roadmap/'
          css_class: 'road'
        - name: Contribute
          href: '/ogm/contribute/'
          css_class: 'users'
        - name: Paid support
          href: '/ogm/support/'
          css_class: 'doctor'
        - name: FAQ
          href: '/ogm/faq/'
          css_class: 'circle help'
      extern:
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-ogm'
          css_class: 'code'
        - name: Issue tracker
          href: 'https://hibernate.atlassian.net/browse/OGM'
          css_class: 'bug'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'lock'
        - name: Forum
          href: 'https://forum.hibernate.org/viewforum.php?f=31'
          css_class: 'comments'
        - name: CI
          href: 'http://ci.hibernate.org/job/hibernate-ogm-master/'
          css_class: 'treatment'
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/ogm'
          css_class: 'edit'
 #other projects would come here

####################################################################################################
# Asciidoctor config
####################################################################################################
asciidoctor:
  :safe: safe
  :attributes:
    #sitename: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    toclevels: 3
    icons: font
    source-highlighter: coderay
    coderay-css: style

####################################################################################################
# Site Profiles
####################################################################################################
# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jquery_js_url: https://code.jquery.com/jquery-3.1.1
    semantic_ui_js_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_js_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    semantic_ui_css_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_css_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    project_images_url: /cache/static.jboss.org/images/hibernate
    enable_google_analytics: false
    news_feed_root_url: http://staging.in.relation.to/feeds
  test:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jquery_js_url: https://code.jquery.com/jquery-3.1.1
    semantic_ui_js_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_js_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    semantic_ui_css_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_css_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    project_images_url: /cache/static.jboss.org/images/hibernate
    enable_google_analytics: false
    news_feed_root_url: http://in.relation.to/feeds
  staging:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jquery_js_url: https://code.jquery.com/jquery-3.1.1
    semantic_ui_js_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_js_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    semantic_ui_css_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_css_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    project_images_url: http://static.jboss.org/images/hibernate
    wget:
      #we don't need to download cached resources when in production
      enabled: false
    base_url: http://staging.hibernate.org
    enable_google_analytics: false
    news_feed_root_url: http://staging.in.relation.to/feeds
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jquery_js_url: https://code.jquery.com/jquery-3.1.1
    semantic_ui_js_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_js_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    semantic_ui_css_url: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic
    slick_css_url: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick
    project_images_url: http://static.jboss.org/images/hibernate
    wget:
      #we don't need to download cached resources when in production
      enabled: false
    base_url: http://hibernate.org
    enable_google_analytics: true
    news_feed_root_url: http://in.relation.to/feeds

google_analytics: 
  account: UA-45270411-1
