# Default page title
title: Hibernate

# Project id name
project: hibernate

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

# project specific information
projects:
  ##################################################################################################
  # ORM
  ##################################################################################################
  orm:
    name: Hibernate ORM
    icon: 'icon-table'
    sourceforge_url: http://sourceforge.net/projects/hibernate/files/hibernate4/
    zip_file: hibernate-release-VERSION.zip
    group_id: org.hibernate
    artifact_id: hibernate-core
    reference_doc_prefix_url: http://docs.jboss.org/hibernate/orm/
    reference_doc_type: manual
    reference_pdf:
    javadoc_path: javadocs
    getting_started: /orm/documentation/getting-started
    license:
      name: LGPL V2.1
      url: http://hibernate.org/license/
    menu:
      intern:
        - name: About
          href: '/orm/'
          css_class: 'icon-fixed-width icon-home'
        - name: Downloads
          href: '/orm/downloads/'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: '/orm/documentation/'
          css_class: 'icon-fixed-width icon-book'
        - name: Tooling
          href: '/orm/tooling/'
          css_class: 'icon-fixed-width icon-wrench'
        - name: Paid support
          href: '/orm/support/'
          css_class: 'icon-fixed-width icon-user-md'
        - name: Get Certified
          href: '/orm/certification/'
          css_class: 'icon-fixed-width icon-certificate'
        - name: FAQ
          href: '/orm/faq/'
          css_class: 'icon-fixed-width icon-question'
        - name: Roadmap
          href: '/orm/roadmap/'
          css_class: 'icon-fixed-width icon-road'
        - name: Contribute
          href: '/orm/contribute/'
          css_class: 'icon-fixed-width icon-beer'
      extern:
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate'
          css_class: 'icon-fixed-width icon-edit'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HHH'
          css_class: 'icon-fixed-width icon-exclamation-sign'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'icon-fixed-width icon-lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-orm'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'http://ci.hibernate.org/'
          css_class: 'icon-fixed-width icon-stethoscope'

  ##################################################################################################
  # Search
  ##################################################################################################
  search:
    name: Hibernate Search
    icon: 'icon-search'
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-search/
    zip_file: hibernate-search-VERSION-dist.zip
    group_id: org.hibernate
    artifact_id: hibernate-search
    reference_doc_prefix_url: http://docs.jboss.org/hibernate/search/
    reference_doc_type: reference
    reference_pdf: hibernate_search_reference.pdf
    javadoc_path: api
    getting_started: /search/documentation/getting-started
    license:
      name: LGPL v2.1
      url: https://raw.github.com/hibernate/hibernate-search/master/lgpl.txt
    menu:
      intern:
        - name: About
          href: '/search/'
          css_class: 'icon-fixed-width icon-home'
        - name: Downloads
          href: '/search/downloads/'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: '/search/documentation/'
          css_class: 'icon-fixed-width icon-book'
        - name: Paid support
          href: '/search/support/'
          css_class: 'icon-fixed-width icon-user-md'
        - name: FAQ
          href: '/search/faq/'
          css_class: 'icon-fixed-width icon-question'
        - name: Roadmap
          href: '/search/roadmap/'
          css_class: 'icon-fixed-width icon-road'
        - name: Contribute
          href: '/search/contribute/'
          css_class: 'icon-fixed-width icon-beer'
      extern:
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/search'
          css_class: 'icon-fixed-width icon-edit'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HSEARCH'
          css_class: 'icon-fixed-width icon-exclamation-sign'
          #  icon-bug only in font-awesome 3.2
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'icon-fixed-width icon-lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-search'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'http://ci.hibernate.org/job/hibernate-search-master/'
          css_class: 'icon-fixed-width icon-stethoscope'

  ##################################################################################################
  # Tools
  ##################################################################################################
  tools:
    name: Hibernate Tools
    icon: 'icon-wrench'
    #sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-search/
    #zip_file: hibernate-search-VERSION-dist.zip
    #group_id: org.hibernate
    #artifact_id: hibernate-search
    #reference_doc_prefix_url: http://docs.jboss.org/hibernate/search/
    #reference_doc_type: reference
    #reference_pdf: hibernate_search_reference.pdf
    #javadoc_path: api
    #getting_started: /search/documentation/getting-started
    license:
      name: LGPL v2.1
      url: https://github.com/hibernate/hibernate-tools/blob/master/lgpl.txt
    menu:
      intern:
        - name: About
          href: '/tools/'
          css_class: 'icon-fixed-width icon-home'
      extern:
        - name: Downloads
          href: 'http://www.jboss.org/tools/download/'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: 'http://www.jboss.org/tools/docs/'
          css_class: 'icon-fixed-width icon-book'
          #TODO add FAQ, Roadmap and Contribute page
          #- name: FAQ
          #  href: '/search/faq/'
          #  css_class: 'icon-fixed-width icon-question'
          #- name: Roadmap
          #  href: '/search/roadmap/'
          #  css_class: 'icon-fixed-width icon-road'
          #- name: Contribute
          #  href: '/search/contribute/'
          #  css_class: 'icon-fixed-width icon-beer'
        - name: Wiki
          href: 'https://community.jboss.org/en/tools'
          css_class: 'icon-fixed-width icon-edit'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HBX'
          css_class: 'icon-fixed-width icon-exclamation-sign'
          #  icon-bug only in font-awesome 3.2
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'icon-fixed-width icon-lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-tools'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'http://hudson.jboss.org/hudson/job/hibernate-tools-trunk/'
          css_class: 'icon-fixed-width icon-stethoscope'

  ##################################################################################################
  # Validator
  ##################################################################################################
  validator:
    name: Hibernate Validator
    icon: 'icon-check'
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-validator/
    zip_file: hibernate-validator-VERSION-dist.zip
    group_id: org.hibernate
    artifact_id: hibernate-validator
    reference_doc_prefix_url: http://docs.jboss.org/hibernate/validator/
    reference_doc_type: reference
    reference_pdf: hibernate_validator_reference.pdf
    javadoc_path: api
    getting_started: /validator/documentation/getting-started
    license:
      name: ASL v2
      url: https://raw.github.com/hibernate/hibernate-validator/master/license.txt
    menu:
      intern:
        - name: About
          href: '/validator/'
          css_class: 'icon-fixed-width icon-home'
        - name: Downloads
          href: '/validator/downloads/'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: '/validator/documentation/'
          css_class: 'icon-fixed-width icon-book'
        - name: Tooling
          href: '/validator/tooling/'
          css_class: 'icon-fixed-width icon-wrench'
        - name: Paid support
          href: '/validator/support/'
          css_class: 'icon-fixed-width icon-user-md'
        - name: FAQ
          href: '/validator/faq/'
          css_class: 'icon-fixed-width icon-question'
        - name: Roadmap
          href: '/validator/roadmap/'
          css_class: 'icon-fixed-width icon-road'
        - name: Contribute
          href: '/validator/contribute/'
          css_class: 'icon-fixed-width icon-beer'
      extern:
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/validator'
          css_class: 'icon-fixed-width icon-edit'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HV'
          css_class: 'icon-fixed-width icon-exclamation-sign'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'icon-fixed-width icon-lock'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-validator'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'https://hibernate-validator.ci.cloudbees.com/'
          css_class: 'icon-fixed-width icon-stethoscope'

  ##################################################################################################
  # OGM
  ##################################################################################################
  ogm:
    name: Hibernate OGM
    icon: 'icon-sitemap'
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-ogm/
    zip_file: hibernate-ogm-VERSION-dist.zip
    group_id: org.hibernate.ogm
    artifact_id: hibernate-ogm-*
    reference_doc_prefix_url: http://docs.jboss.org/hibernate/ogm/
    reference_doc_type: reference
    reference_pdf: hibernate_ogm_reference.pdf
    javadoc_path: api
    getting_started: /ogm/documentation/getting-started
    license:
      name: LGPL
      url: http://www.gnu.org/licenses/lgpl.html
    menu:
      intern:
        - name: About
          href: '/ogm/'
          css_class: 'icon-fixed-width icon-home'
        - name: Downloads
          href: '/ogm/downloads/'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: '/ogm/documentation/'
          css_class: 'icon-fixed-width icon-book'
        - name: Paid support
          href: '/ogm/support/'
          css_class: 'icon-fixed-width icon-user-md'
        - name: FAQ
          href: '/ogm/faq/'
          css_class: 'icon-fixed-width icon-question'
        - name: Roadmap
          href: '/ogm/roadmap/'
          css_class: 'icon-fixed-width icon-road'
        - name: Contribute
          href: '/ogm/contribute/'
          css_class: 'icon-fixed-width icon-beer'
      extern:
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/ogm'
          css_class: 'icon-fixed-width icon-edit'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/OGM'
          css_class: 'icon-fixed-width icon-exclamation-sign'
        - name: Security issue
          href: 'https://access.redhat.com/security/team/contact/'
          css_class: 'icon-fixed-width icon-lock'
        - name: Forum
          href: 'https://forum.hibernate.org/viewforum.php?f=31'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-ogm'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'http://ci.hibernate.org/job/hibernate-ogm-master/'
          css_class: 'icon-fixed-width icon-stethoscope'
 #other projects would come here

####################################################################################################
# File merger
####################################################################################################
# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-misc.js
    - /javascripts/_jbossorg-tabzilla.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js

####################################################################################################
# WGET
####################################################################################################
# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/images/example/
    - http://static.jboss.org/images/hibernate/

####################################################################################################
# Asciidoctor config
####################################################################################################
asciidoctor:
  :safe: safe
  :attributes:
    #sitename: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    toclevels: 3
    icons: font
    source-highlighter: coderay
    coderay-css: style

####################################################################################################
# Site Profiles
####################################################################################################
# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/hibernate
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.3/bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    #bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.3/bootstrap-community
  test:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/hibernate
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.3/bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    #bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.3/bootstrap-community
    # base_url: http://hibernate.org.beanvalidation.org
  staging:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/hibernate
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.3/bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    #bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.3/bootstrap-community
    wget:
      #we don't need to download cached resources when in production
      enabled: false
    base_url: http://staging.hibernate.org
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/hibernate
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.3/bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    #bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.3/bootstrap-community
    wget:
      #we don't need to download cached resources when in production
      enabled: false
    base_url: http://hibernate.org

google_analytics: 
  account: UA-45270411-1
