= Governance
:toc:
:awestruct-layout: community-standard

This document outlines the governance model for Hibernate projects.
This governance model is designed to uphold the principles of transparency, open collaboration, and community involvement.

[[roles]]
== Roles and Responsibilities

- **Contributors:** Anyone who contributes to Hibernate projects in any form.
- **Members:** Contributors eligible for write access to a Hibernate code repository.
  Responsible for reviewing and merging contributions in their area of expertise.
- **Project Leaders:** Members (at most one per code repository) with higher decision power whenever the project they lead is affected.
  Responsible for steering project direction, and for enforcing compliance with requirements of the Commonhaus Foundation.

Small or inactive projects may not have a leader,
in which case Members interested in the project will steer the project direction.

[[decision-making]]
== Decision-Making

Hibernate projects follow a common decision-making process.

Consensus-seeking (lazy consensus)::
Hibernate projects primarily aim for a consensus-based decision-making process,
where Members and active contributors discuss and come to an agreement.
+
In practice, this involves:
+
* Discussing matters openly, to facilitate others joining the discussions and expressing concerns.
* Taking into account every contributor's opinion, regardless of their role.

+
Actual implementation of consensus decision-making is up to Members and can vary based on the audience and criticality of the discussion.
Inspiration may be found in
the https://community.apache.org/committers/decisionMaking.html[Lazy Consensus model as defined by the Apache Foundation],
and in https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1825&context=sociologyfacpub[Martha's Rules].
Conflict Resolution::
If conflicts arise, Members are responsible for facilitating a resolution.
+
Project Leaders hold the power to make the final decision, be it individually for the project they lead,
or collectively for cross-project matters.
+
As a last resort, in particular in case of disagreement about the decision-making process,
the https://www.commonhaus.org/bylaws/cf-council.html[Commonhaus Foundation Council] (CFC) can be asked to mediate the discussion.

[[role-granting-revoking]]
== Role granting/revoking

The role of Member or Project Leader is granted or revoked through the <<decision-making,decision-making process>>,
with additional restrictions:

1. The discussion must happen on the Hibernate development mailing list, as listed in the link:/community[Community page on this website].
// This prevents a Project Leader overruling their own revocation, in particular.
2. The opinion of the Members or Project Leader whose role is being discussed does not factor into the decision.
// This is long on purpose, to eliminates the risk of a decision being taken "in absentia" during e.g. holidays.
// The assumption is that decisions around the project can be taken collectively, or by the previous leader, in the interim.
3. Discussions regarding the role of Project Leader may not last less than 30 days.

Eligible candidates are:

For the role of Member::
Any contributor.
For the role of Project Leader::
Any contributor to the project they will lead, provided the candidate is a Commonhaus Foundation member,
// TODO update link upon the PR getting merged.
and agrees to become a Signatory of the https://github.com/commonhaus/foundation/pull/219/files#diff-64f58a8e70e16b011f35a30256797c538e6a951da4e9985943b55f4abe6e94b1[Commonhaus Fiscal Sponsorship Agreement] before taking on their new role.

Members and Project Leaders keep their role indefinitely, unless they resign or a new decision revokes their role.

The list of Members and Project Leaders is kept up-to-date on the link:/community/team["Team" page] of this website.

[[code-of-conduct]]
== Code of Conduct

All participants in Hibernate projects are expected to adhere to the https://www.commonhaus.org/policies/code-of-conduct/[Commonhaus Foundation Code of Conduct]. Please ensure you are familiar with its guidelines and expectations, as it's essential for maintaining a positive and collaborative environment.

[[trademark-policy]]
== Trademark Policy

The Hibernate logos, icons, and domain names are protected by trademark rights. Usage of these trademarks must adhere to the https://www.commonhaus.org/policies/trademark-policy/[Commonhaus Foundation Trademark Policy].

[[contributing]]
== Contributing

We welcome all forms of contribution, from code improvements to documentation and design. For details on how to contribute and the process your contributions will follow, please read our link:/community/contribute/[Contributing Guidelines].
