= Hibernate Community
Emmanuel Bernard
:awestruct-layout: community-news

Hibernate is first and foremost an open source community.
Each project is released under an open source license.
All code, issues and discussions are done in the open.

Read about our link:/community/governance[governance model].

== Ask questions & find answers

You have a question on one of the Hibernate projects?

Documentation::
The best is to first check the documentation. Yes it looks boring but knowing a tool makes a real difference.
http://community.jboss.org/en/hibernate/[Wiki]::
The wiki nicely complements the reference documentation and is improved by the community at large.
http://forum.hibernate.org[Forum]::
After the documentation, probably the best place to look in.
irc://irc.freenode.net/#hibernate[IRC user channel]::
If you prefer live conversations like we do, join the IRC channel +#hibernate+ on https://www.freenode.net[Freenode].

== Stay connected & up to date

http://in.relation.to[Blog]::
The Hibernate team maintains a http://in.relation.to[team blog] where we announce the latest releases, describe new features and discuss Hibernate in general.
https://lists.jboss.org/mailman/listinfo/hibernate-announce[Announcement mailing list]::
Very low volume list for general announcements such as release notifications.
https://twitter.com/hibernate[*Twitter*]::
You know, like a twitter account.
https://plus.google.com/112681342290762837955/posts[*Google +*]::
Links of and around the community are posted there.

== Contribute

There are many forms of contribution, from helping other users on the forum, to opening qualified issues, writing documentation or provide code patches.

If you want to know more, look through one of these avenues:

https://hibernate.atlassian.net[Issue tracker]::
JIRA is where all tasks are reported and life cycle maintained. In particular look for the ones https://hibernate.atlassian.net/issues/?jql=status%20in%20(Open%2C%20Reopened%2C%20%22Awaiting%20Test%20Case%22)%20AND%20%22Suitable%20for%20new%20contributors%22%20%3D%20%22Yes%2C%20likely%22%20ORDER%20BY%20updated%20DESC[suitable for new contributors].
https://lists.jboss.org/mailman/listinfo/hibernate-dev[Development mailing list]::
Discussion list for developers to brainstorm ideas. Between JIRA and this mailing, you will not miss any discussion.
irc://irc.freenode.net/#hibernate-dev[IRC development channel]::
Join the development channel on Freenode where Hibernate developers and contributors discuss development of Hibernate.
To join +#hibernate-dev+ you will have to register your nickname. Just follow the instructions http://freenode.net/faq.shtml#nicksetup[on Freenode].
https://github.com/hibernate/[GitHub]::
It's all code in the end. Even this website is on https://github.com/hibernate/hibernate.org[a GitHub hosted repo].
Follow what we do on GitHub and open pull requests for your contributions.
We loooove pull requests :-)

== Miscellaneous

https://lists.jboss.org/mailman/listinfo/hibernate-commits[Hibernate commits mailing list]::
Source control commit notifications.
https://lists.jboss.org/mailman/listinfo/hibernate-issues[Hibernate issues notification mailing list]::
Automatic notifications from issue tracking (JIRA).
