= Come and join us!
Emmanuel Bernard
:awestruct-layout: community-news

Hibernate is first and foremost an open source community.
Code, issues and discussions are in the open and each project is released under an open source license.

[questions]
== Ask questions & find answers

If you have a question regarding one of our projects, the following resources will help you
finding the answer:

Documentation::
Best to first check the documentation. Yes it sounds boring, but knowing a tool makes the difference.
+++<br />
<div class="ui labels blue">
<a class="ui label" href="/orm/documentation/"><i class="icon book"></i>ORM</a>
<a class="ui label" href="/search/documentation/"><i class="icon book"></i>Search</a>
<a class="ui label" href="/validator/documentation/"><i class="icon book"></i>Validator</a>
<a class="ui label" href="/ogm/documentation/"><i class="icon book"></i>OGM</a>
<a class="ui label" href="http://tools.jboss.org/documentation/"><i class="icon book"></i>Tools</a>
<a class="ui label" href="/reactive/documentation/"><i class="icon book"></i>Reactive</a>
</div>
+++

https://stackoverflow.com/[Stack Overflow]::
After the documentation, probably the best place to look for answers. We actively monitor the following tags:
+++<br />
<div class="ui labels blue">
<a class="ui label" href="https://stackoverflow.com/questions/tagged/hibernate">hibernate</a>
<a class="ui label" href="https://stackoverflow.com/questions/tagged/hibernate-search">hibernate-search</a>
<a class="ui label" href="https://stackoverflow.com/questions/tagged/hibernate-validator">hibernate-validator</a>
<a class="ui label" href="https://stackoverflow.com/questions/tagged/hibernate-ogm">hibernate-ogm</a>
<a class="ui label" href="https://stackoverflow.com/questions/tagged/hibernate-tools">hibernate-tools</a>
<a class="ui label" href="https://stackoverflow.com/questions/tagged/hibernate-reactive">hibernate-reactive</a>
</div>
+++

https://discourse.hibernate.org[Forum]::
If your question doesn't fit the Stack Overflow format, our forum is here for you. Come join us and discuss! We have a category for each project:
+++<br />
<div class="ui labels blue">
<a class="ui label" href="https://discourse.hibernate.org/c/hibernate-orm">Hibernate ORM</a>
<a class="ui label" href="https://discourse.hibernate.org/c/hibernate-search">Hibernate Search</a>
<a class="ui label" href="https://discourse.hibernate.org/c/hibernate-validator">Hibernate Validator</a>
<a class="ui label" href="https://discourse.hibernate.org/c/hibernate-ogm">Hibernate OGM</a>
<a class="ui label" href="https://discourse.hibernate.org/c/hibernate-tools">Hibernate Tools</a>
<a class="ui label" href="https://discourse.hibernate.org/c/hibernate-reactive">Hibernate Reactive</a>
</div>
+++

https://hibernate.zulipchat.com/[Chat]::
If you prefer live conversations (we do), join the Hibernate User help channel,
powered by https://zulipchat.com/[Zulip]:
+++<br />
<a class="ui mini button labeled icon primary" href="https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user"><i class="icon users"></i>hibernate-user</a>
+++
+
NOTE: You will need to register an account in order to access the chat; registration is free and only requires an email address.
You can also log in using external accounts such as your GitHub account.
+
NOTE: Bear in mind that people who can help answer your questions may not even see that message for hours - be patient for a reply.

https://hibernate.atlassian.net[Issue tracker]::
If you need to report a bug or request a new feature, look for a similar one on JIRA.
If you don't find any, create a ticket.
Here are the pages dedicated to each project:
+++<br />
<div class="ui labels blue">
<a class="ui label" href="https://hibernate.atlassian.net/browse/HHH">Hibernate ORM</a>
<a class="ui label" href="https://hibernate.atlassian.net/browse/HSEARCH">Hibernate Search</a>
<a class="ui label" href="https://hibernate.atlassian.net/browse/HV">Hibernate Validator</a>
<a class="ui label" href="https://hibernate.atlassian.net/browse/OGM">Hibernate OGM</a>
<a class="ui label" href="https://hibernate.atlassian.net/browse/HBX">Hibernate Tools</a>
<a class="ui label" href="https://github.com/hibernate/hibernate-reactive/issues">Hibernate Reactive</a>
</div>
+++
+
NOTE: If you're unsure whether you found a bug or simply made a mistake,
please try to get help on Stack Overflow or on our forums first (see above).

== Stay connected & up to date

http://in.relation.to[Blog]::
The Hibernate team maintains a http://in.relation.to[team blog] where we announce the latest releases, 
describe new features and discuss Hibernate in general.

https://lists.jboss.org/mailman/listinfo/hibernate-announce[Announcement mailing list]::
Very low volume list for general announcements such as release notifications.

https://twitter.com/hibernate[*Twitter*]::
You know, like a twitter account.
https://plus.google.com/112681342290762837955/posts[*Google +*]::
Links of and around the community are posted there.

[contribute]
== Contribute

There are many forms of contribution, from helping other users on the forum, to opening qualified 
issues, writing documentation or providing code patches.

If you want to know more, look through one of these avenues:

https://hibernate.atlassian.net[Issue tracker]::
JIRA is where all tasks are reported and tracked. In particular look for the ones marked 
https://hibernate.atlassian.net/issues/?filter=13761[suitable for new contributors].

https://lists.jboss.org/mailman/listinfo/hibernate-dev[Development mailing list]::
Discussion list for developers to brainstorm ideas. Between JIRA and this mailing, you will not miss 
any discussion.

https://hibernate.zulipchat.com/chat[Zulip]::
The Hibernate team maintains multiple development-oriented https://zulipchat.com/[Zulip] channels (called "streams"), one per project.
+++<br />
<div class="ui labels blue">
<a class="ui label" href="https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev">hibernate-orm-dev</a>
<a class="ui label" href="https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev">hibernate-search-dev</a>
<a class="ui label" href="https://hibernate.zulipchat.com/#narrow/stream/132093-hibernate-validator-dev">hibernate-validator-dev</a>
<a class="ui label" href="https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev">hibernate-ogm-dev</a>
<a class="ui label" href="https://hibernate.zulipchat.com/#narrow/stream/132104-hibernate-tooling-dev">hibernate-tooling-dev</a>
<a class="ui label" href="https://hibernate.zulipchat.com/#narrow/stream/205413-hibernate-reactive-dev">hibernate-reactive-dev</a>
</div>
+++
+
NOTE: You will need to register an account in order to access the chat; registration is free and only requires an email address.
You can also log in using external accounts such as your GitHub account.
Once you're logged in, you will need to explicitly subscribe to streams by clicking the settings icon on the top right,
then https://hibernate.zulipchat.com/#streams/all[manage streams].


https://github.com/hibernate/[GitHub]::
It's all code in the end. Even this website is on https://github.com/hibernate/hibernate.org[a GitHub hosted repo].
Follow what we do on GitHub and open pull requests for your contributions.
We loooove pull requests :-)

== Miscellaneous

https://lists.jboss.org/mailman/listinfo/hibernate-commits[Hibernate commits mailing list]::
Source control commit notifications.

https://lists.jboss.org/mailman/listinfo/hibernate-issues[Hibernate issues notification mailing list]::
Automatic notifications from issue tracking (JIRA).
