= Setting up Eclipse to contribute to Hibernate projects
:awestruct-layout: community-standard
:toc:
:toc-placement: preamble
:toc-title: Contents

Official website: https://www.eclipse.org/eclipseide/

== Build system integration

=== Identifying the build system

Some of the Hibernate projects use Maven, some others use Gradle.
After you check out the project from https://github.com/hibernate/[GitHub],
check if there is a `pom.xml` file in the root of the sources: that means it's a Maven project.
If there is a `build.gradle` file instead, then you will need to use Gradle to build it.

=== Maven

We recommend using the excellent m2e plugin.
This plugin is commonly already installed in Eclipse;
if you suspect it's missing you should be able to find it under "Help" -> "Install New Software".

When importing a Hibernate project using m2e, Eclipse might suggest to install additional plugins,
for example to handle annotation processors.
It will ask for permission to automatically download the additional plugins;
we suggest to allow this as it simplifies development.

=== Gradle

You will need to install "Buildship", the Gradle tools for Eclipse.

Installing it is very simple: just follow
http://www.vogella.com/tutorials/EclipseGradle/article.html[this step by step tutorial].

After having installed the Gradle tooling, import the project using the "gradle wrapper" approach -- which is the default.
This might take several minutes, as the Gradle build might need to download dependencies in the background,
or do some work to analyze the project.

==== Specific instructions for Hibernate ORM in Eclipse

If you're importing the flagship project Hibernate ORM,
the import process gets a bit more tedious as the Eclipse/Gradle integration is still a bit limited.

After importing the project, you will have Eclipse mention several errors because of "circular dependency problems".
The project actually doesn't have any circular dependency but the Gradle integration leads it to believe this;
you will have to go in "Window" -> "Preferences" -> "Java" -> "Compiler" -> "Building",
find the "Circular Dependencies" problem and have Eclipse ignore the problem
by categorizing it as "Warning" rather than "Error".

Next, for several modules you will have to manually add some generated sources to the source folders.
For example for the hibernate-core module, you will need to add `target/generated-src/antlr/main`,
`target/generated-src/apt/main`, `target/generated-src/apt/test` and `target/generated-src/jaxb/main`.
Note that these directories might be hidden by default,
check your Filter options and uncheck "Gradle build folder".
Use "Build Path" -> "Use as Source Folder" on each of these.

Finally, you will have to manually add the ANT and JBoss Logger dependencies.

== Code style

Each Hibernate project includes a set of build plugins to format and verify the code style of the sources.
Please refer to the particular project contributing guide for more details.

[NOTE]
====
If the project build does not define a fully automated code formatter,
please avoid reformatting large sections of code, especially when providing a patch:
we would love to have the diffs highlight the changes that matter.
====

== Code templates

All top-level Hibernate projects are Apache 2.0 licensed and use the following header format:

[source,java]
----
/*
* SPDX-License-Identifier: Apache-2.0
* Copyright Red Hat Inc. and Hibernate Authors
*/
----

Note that each project has a license build plugin configured to check for the correct license header formatting.
At the same time, such a plugin provides options to add the missing headers.
Please refer to the particular project build for more details.

== Running tests in Eclipse

Some tests involving integration with JGroups and/or Infinispan will start a network connection to themselves
(via localhost) to simulate a cluster of computers.
Many JVMs default to IPv6 for this, so either you have that configured correctly
or you might want to start these tests with these JVM properties set:

[source]
----
-Djava.net.preferIPv4Stack=true -Djgroups.bind_addr=127.0.0.1
----

== Debugging

When debugging, Eclipse might invoke `toString()` methods on the objects you select for inspection.
This operation could trigger initialization of proxies and so affect the debugged object state.
Using Eclipse you can customize the way it shows objects: look into "Detail formatters"
and the link:intellij-idea[IntelliJ IDEA page] for some ideas.
You could avoid including lazy-loaded details in your `toString()` implementations:
it also helps to avoid unintended loading during logging, a frequent mistake having terrible effects on performance.

== Beyond

If you want to contribute to Hibernate projects, start link:../guidelines[here].

