:awestruct-layout: project-releases-series
:awestruct-project: validator
:awestruct-series_version: "9.0"

=== Jakarta EE 11

Hibernate Validator 9.0 is targeted to be the reference implementation for Jakarta Bean Validation 3.1 in Jakarta EE 11.

Upgrade to Hibernate Validator 9 is required if you are moving to Jakarta EE 11.

With Jakarta EE 11 upgrade the minimum required Java version is 17.

=== New constraints

This release also brings new constraints.

==== Country-specific South Korean RRN constraint

The new constraint `@KorRRN` was added to validate the Korean resident registration numbers.

==== Bitcoin address constraint

The new `@BitcoinAddress` constraint was added to validate whether BTC (Bitcoin) addresses are well-formed.

==== Alphanumeric CNPJ

A new configuration option was added to the `@CNPJ` constraint to allow validating the upcoming alphanumeric format of the number.

=== Hibernate Validator BOM

Hibernate Validator now offers a BOM providing dependency management for all of its published artifacts.
It can be imported as part of your dependency management to keep the versions of Hibernate Validator artifacts aligned.

=== Removal of the Security Manager integration

With the security manager being deprecated without an alternative for some time now,
we took the opportunity provided by the specification requirement of the minimum Java version
to remove the integration of the Security Manager from Hibernate Validator.

=== Removal of the deprecated constraints, configuration properties and methods

With the new major release of Hibernate Validator some of the constraints, configuration properties,
and public API methods/classes that have been deprecated for a few major versions now are removed.
For a detailed list of removed deprecated items see the link:/validator/documentation/migration-guide#9-0-x[migration guide].

=== OSGi integration

Starting with Hibernate Validator 9.0, the Hibernate team no longer tests nor maintains the OSGi integration.
For users who would want to experiment with Hibernate Validator in an OSGi environment,
we will keep the existing manifest entries in place as they were.

[WARNING]
====
Even though we no longer maintain the Hibernate Validator OSGi integration,
we do encourage the community members interested in it to come forward with pull requests
if they encounter some issues. In such a case, we will try to guide the submitter through the contribution process
and assess the suggested patch for inclusion in the build.
====
