# SPDX-License-Identifier: Apache-2.0
# Copyright Red Hat Inc. and Hibernate Authors
name: GH Actions CI

on:
  pull_request:
    branches:
      - production

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Build site
        run: |
          docker run --pull always --rm -t -u "$(id -u):$(id -g)" -v "$WORKSPACE_DIR":/home/dev/website:rw quay.io/hibernate/awestruct-build-env:latest "rake setup && rake clean[all] gen[production]"
        env:
          WORKSPACE_DIR: ${{ github.workspace }}

      - name: Upload site preview
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: docs-preview
          path: _site/
          retention-days: 1
